export const stateExcelMapping = {
  "Andhara Pradesh": [
    "/Andhara Pradesh/Abstract Of Shops and Establishment Act 1988 (Telugu Version).pdf",
    "/Andhara Pradesh/Abstract Under Andhra Pradesh Shops and Establishment Act,1988.pdf",
    "/Andhara Pradesh/BOCW/Abstract Under Andhra Pradesh Building And Other Construction Workers And Rules1999.docx",
    "/Andhara Pradesh/BOCW/Andhra Pradesh (Issuance Of Integrated Registration And Furnishing Of Combined Returns Under Various Labour Laws By Certain Establishments) Act, 2015.pdf",
    "/Andhara Pradesh/BOCW/FORM B - Combined Annual Returns.xlsx",
    "/Andhara Pradesh/BOCW/Form I (1).XLSX",
    "/Andhara Pradesh/BOCW/FORM I (2).xlsx",
    "/Andhara Pradesh/BOCW/Form I.XLSX",
    "/Andhara Pradesh/BOCW/Form II.XLSX",
    "/Andhara Pradesh/BOCW/FORM IV (1).xlsx",
    "/Andhara Pradesh/BOCW/FORM IV.xlsx",
    "/Andhara Pradesh/BOCW/FORM XI.xlsx",
    "/Andhara Pradesh/BOCW/FORM XII.xlsx",
    "/Andhara Pradesh/BOCW/FORM XIII.xlsx",
    "/Andhara Pradesh/BOCW/FORM XIV.xlsx",
    "/Andhara Pradesh/BOCW/Form XIX.XLSX",
    "/Andhara Pradesh/BOCW/FORM XV.xlsx",
    "/Andhara Pradesh/BOCW/Form XVI.XLSX",
    "/Andhara Pradesh/BOCW/Form XVII.XLSX",
    "/Andhara Pradesh/BOCW/Form XVIII.XLSX",
    "/Andhara Pradesh/BOCW/Form XX.XLSX",
    "/Andhara Pradesh/BOCW/Form XXI.XLSX",
    "/Andhara Pradesh/BOCW/Form XXII.XLSX",
    "/Andhara Pradesh/BOCW/Form XXIII.XLSX",
    "/Andhara Pradesh/BOCW/Form XXIV.XLSX",
    "/Andhara Pradesh/BOCW/FORM XXVI.xlsx",
    "/Andhara Pradesh/BOCW/FORM XXVII.xlsx",
    "/Andhara Pradesh/BOCW/FORM XXVIII.xlsx",
    "/Andhara Pradesh/BOCW/FORM XXX.xlsx",
    "/Andhara Pradesh/CA Certificate.pdf",
    "/Andhara Pradesh/Child Labour/Abstract of Child and Adolescent Labour Prohibition And Regulation Act 1986.pdf",
    "/Andhara Pradesh/Child Labour/Abstract of Child Labour Prohibition And Regulation Act 1986 (Telugu Version).pdf",
    "/Andhara Pradesh/Child Labour/Child Labour Notice.docx",
    "/Andhara Pradesh/Child Labour/FORM A.docx",
    "/Andhara Pradesh/CLRA/Abstract Of The Contract Labour (Regulation And Abolition) Act, 1970 And The Contract Labour (Regulation And Abolition) Central Rules, 1971 (English Version).pdf",
    "/Andhara Pradesh/CLRA/Abstract Of The Contract Labour (Regulation And Abolition) Act, 1970 And The Contract Labour (Regulation And Abolition) Central Rules, 1971 (Telugu Version).pdf",
    "/Andhara Pradesh/CLRA/Andhra Pradesh (Issuance Of Integrated Registration And Furnishing Of Combined Returns Under Various Labour Laws By Certain Establishments) Act, 2015.pdf",
    "/Andhara Pradesh/CLRA/Display Of Notice Regarding Rates Of Wages Etc-Andhra Pradesh.doc",
    "/Andhara Pradesh/CLRA/FORM A.docx",
    "/Andhara Pradesh/CLRA/FORM B - Combined Annual Returns.xlsx",
    "/Andhara Pradesh/CLRA/FORM B.docx",
    "/Andhara Pradesh/CLRA/FORM C.docx",
    "/Andhara Pradesh/CLRA/FORM IV.docx",
    "/Andhara Pradesh/CLRA/FORM V.docx",
    "/Andhara Pradesh/CLRA/FORM VI A (1).docx",
    "/Andhara Pradesh/CLRA/FORM VI A.docx",
    "/Andhara Pradesh/CLRA/FORM VI-B (1).docx",
    "/Andhara Pradesh/CLRA/FORM VI-B.docx",
    "/Andhara Pradesh/CLRA/FORM VII (1).docx",
    "/Andhara Pradesh/CLRA/FORM VII.docx",
    "/Andhara Pradesh/CLRA/FORM XII.docx",
    "/Andhara Pradesh/CLRA/FORM XIII.docx",
    "/Andhara Pradesh/CLRA/FORM XIV.docx",
    "/Andhara Pradesh/CLRA/FORM XV.docx",
    "/Andhara Pradesh/CLRA/FORM XVI.docx",
    "/Andhara Pradesh/CLRA/FORM XVII.docx",
    "/Andhara Pradesh/CLRA/FORM XX.docx",
    "/Andhara Pradesh/CLRA/FORM XXI.docx",
    "/Andhara Pradesh/CLRA/FORM XXII.docx",
    "/Andhara Pradesh/CLRA/FORM XXIII.docx",
    "/Andhara Pradesh/CLRA/FORM XXIV.docx",
    "/Andhara Pradesh/Compession/FORM A.docx",
    "/Andhara Pradesh/Compession/FORM D.docx",
    "/Andhara Pradesh/Compession/FORM EE Report Of Fatal Accidents.docx",
    "/Andhara Pradesh/Compession/FORM F.docx",
    "/Andhara Pradesh/Compession/Returns As To Compensation.xlsx",
    "/Andhara Pradesh/Factory/FORM 18-A.xlsx",
    "/Andhara Pradesh/Factory/FORM 18.xlsx",
    "/Andhara Pradesh/Factory/FORM 19.xlsx",
    "/Andhara Pradesh/Factory/FORM 25 (1).xlsx",
    "/Andhara Pradesh/Factory/FORM 25 (2).xlsx",
    "/Andhara Pradesh/Factory/FORM 25.xlsx",
    "/Andhara Pradesh/Factory/FORM 27 C.xlsx",
    "/Andhara Pradesh/Factory/FORM 2A.xlsx",
    "/Andhara Pradesh/Factory/FORM 38.xlsx",
    "/Andhara Pradesh/Factory/FORM I.docx",
    "/Andhara Pradesh/Factory/FORM II.docx",
    "/Andhara Pradesh/Factory/FORM NO 8B.docx",
    "/Andhara Pradesh/Factory/FORM NO. 11.xlsx",
    "/Andhara Pradesh/Factory/FORM NO. 35.xlsx",
    "/Andhara Pradesh/Factory/FORM NO.5.docx",
    "/Andhara Pradesh/Factory/FORM NO.8A.docx",
    "/Andhara Pradesh/Factory/GNT1720 Employment Of Women During Night Shift In Factories In Andhra Pradesh.pdf",
    "/Andhara Pradesh/FORM 11 Accident Book ESIC.pdf",
    "/Andhara Pradesh/FORM 6 Register Of Employees.xls",
    "/Andhara Pradesh/FORM I Nomination And Declaration Form.docx",
    "/Andhara Pradesh/FORM III Shop & E.xlsx",
    "/Andhara Pradesh/FORM III.docx",
    "/Andhara Pradesh/FORM IV Annual Retrun.docx",
    "/Andhara Pradesh/FORM V Abstract Under The Payment Of Wages Act, 1936 (English Version).pdf",
    "/Andhara Pradesh/FORM V Abstract Under The Payment Of Wages Act, 1936 (Telugu Version).pdf",
    "/Andhara Pradesh/FORM XXVII.xlsx",
    "/Andhara Pradesh/Gartiuty/FORM C Notice Of Closure.docx",
    "/Andhara Pradesh/Gartiuty/FORM F Nomination Form.docx",
    "/Andhara Pradesh/Gartiuty/FORM G Fresh Nomination.docx",
    "/Andhara Pradesh/Gartiuty/FORM I Application For Gratuity By An Employee.docx",
    "/Andhara Pradesh/Gartiuty/FORM J Application For Gratuity By A Nominee.docx",
    "/Andhara Pradesh/Gartiuty/FORM K Application For Gratuity By A Legal Heir.docx",
    "/Andhara Pradesh/Gartiuty/FORM L Notice For Payment Of Gratuity.docx",
    "/Andhara Pradesh/Gartiuty/Notice of Authorised Person under PoG Act (English).doc",
    "/Andhara Pradesh/Gartiuty/Notice of Authorised Person under PoG Act (Telugu).doc",
    "/Andhara Pradesh/Industrial/FORM A.docx",
    "/Andhara Pradesh/Industrial/FORM B.docx",
    "/Andhara Pradesh/Industrial/FORM I (1).docx",
    "/Andhara Pradesh/Industrial/FORM II.docx",
    "/Andhara Pradesh/Industrial/Schedule I.docx",
    "/Andhara Pradesh/LWF/FORM A (1).docx",
    "/Andhara Pradesh/LWF/FORM D.docx",
    "/Andhara Pradesh/LWF/FORM E.docx",
    "/Andhara Pradesh/LWF/FORM F.xlsx",
    "/Andhara Pradesh/LWF/FORM G.docx",
    "/Andhara Pradesh/Migrant/FORM I (1).xlsx",
    "/Andhara Pradesh/Migrant/FORM I.xlsx",
    "/Andhara Pradesh/Migrant/FORM IV.xlsx",
    "/Andhara Pradesh/Migrant/FORM IX.xlsx",
    "/Andhara Pradesh/Migrant/FORM V.xlsx",
    "/Andhara Pradesh/Migrant/FORM VI.xlsx",
    "/Andhara Pradesh/Migrant/FORM XII.xlsx",
    "/Andhara Pradesh/Migrant/FORM XIV.xlsx",
    "/Andhara Pradesh/Migrant/FORM XIX.xlsx",
    "/Andhara Pradesh/Migrant/FORM XV.xlsx",
    "/Andhara Pradesh/Migrant/FORM XVI.xlsx",
    "/Andhara Pradesh/Migrant/FORM XVII.xlsx",
    "/Andhara Pradesh/Migrant/FORM XVIII.xlsx",
    "/Andhara Pradesh/Migrant/FORM XX.xlsx",
    "/Andhara Pradesh/Migrant/FORM XXIII.xlsx",
    "/Andhara Pradesh/Migrant/FORM XXIV.xlsx",
    "/Andhara Pradesh/Migrant/FORM XXV.xlsx",
    "/Andhara Pradesh/Migrant/FORM XXVIII.xlsx",
    "/Andhara Pradesh/PoW Register of wages.xls",
    "/Andhara Pradesh/PT/FORM No. I.xlsx",
    "/Andhara Pradesh/PT/FORM No. II.xlsx",
    "/Andhara Pradesh/PT/FORM No. V PT.xlsx",
    "/Andhara Pradesh/Shop & est/FORM A.xlsx",
    "/Andhara Pradesh/Shop & est/FORM VI.xlsx",
    "/Andhara Pradesh/Shop & est/FORM VII.xlsx",
    "/Andhara Pradesh/Shop & est/FORM X.docx",
    "/Andhara Pradesh/Shop & est/FORM XI.docx",
    "/Andhara Pradesh/Shop & est/FORM XII.docx",
    "/Andhara Pradesh/Shop & est/FORM XXII.docx",
    "/Andhara Pradesh/Shop & est/FORM XXIII.docx",
    "/Andhara Pradesh/Shop & est/FORM XXIV.docx",
    "/Andhara Pradesh/Shop & est/FORM XXV.docx.xlsx",
    "/Andhara Pradesh/Shop & est/FORM XXVI.docx",
    "/Andhara Pradesh/Shop & est/FORM XXVII.docx",
    "/Andhara Pradesh/Wages/Andhra Pradesh (Issuance Of Integrated Registration And Furnishing Of Combined Returns Under Various Labour Laws By Certain Establishments) Act, 2015.pdf",
    "/Andhara Pradesh/Wages/FORM B - Combined Annual Returns.xlsx",
    "/Andhara Pradesh/Wages/FORM I.docx",
    "/Andhara Pradesh/Wages/FORM II.docx",
    "/Andhara Pradesh/Wages/FORM IV.docx",
    "/Andhara Pradesh/Wages/FORM XII Abstract Under Minimum Wages Act, 1948 (English Version).pdf",
    "/Andhara Pradesh/Wages/FORM XII Abstract Under Minimum Wages Act, 1948 (Telugu Version).pdf",
  ],
  "Andman Nicobar": [
    "/Andman Nicobar/CA Certificate.pdf",
    "/Andman Nicobar/CLRA/Abstract Under The Contract Labour (Regulation And Abolition) Act, 1970 (English Version).pdf",
    "/Andman Nicobar/CLRA/Abstract Under The Contract Labour (Regulation And Abolition) Act, 1970 (Hindi Version).pdf",
    "/Andman Nicobar/CLRA/Form A.xlsx",
    "/Andman Nicobar/CLRA/Form B Muster.xlsx",
    "/Andman Nicobar/CLRA/Form B.xlsx",
    "/Andman Nicobar/CLRA/Form C.xlsx",
    "/Andman Nicobar/CLRA/Form D Muster.xlsx",
    "/Andman Nicobar/CLRA/Form I Register of wages.xlsx",
    "/Andman Nicobar/CLRA/FORM II (1).xlsx",
    "/Andman Nicobar/CLRA/FORM II.xlsx",
    "/Andman Nicobar/CLRA/FORM III.xlsx",
    "/Andman Nicobar/CLRA/FORM VII (1).xlsx",
    "/Andman Nicobar/CLRA/FORM VII (2).xlsx",
    "/Andman Nicobar/CLRA/FORM VII (3).xlsx",
    "/Andman Nicobar/CLRA/FORM VII.xlsx",
    "/Andman Nicobar/CLRA/FORM VIII.xlsx",
    "/Andman Nicobar/CLRA/FORM XII Register Of Contractors.xlsx",
    "/Andman Nicobar/CLRA/Form XIII Annexed To The Rationalisation Of Forms And Reports Under Certain Labour Laws Rules, 2017.xlsx",
    "/Andman Nicobar/CLRA/Form XIII Register of Workmen.xlsx",
    "/Andman Nicobar/CLRA/Form XIX Wage Slip.xlsx",
    "/Andman Nicobar/CLRA/Form XVI Muster Roll.xlsx",
    "/Andman Nicobar/CLRA/Form XVII Register of Wages Muster.xlsx",
    "/Andman Nicobar/CLRA/Form XX Register of Deduction.xlsx",
    "/Andman Nicobar/CLRA/Form XXI Register of Fines.xlsx",
    "/Andman Nicobar/CLRA/Form XXII Register of Advances.xlsx",
    "/Andman Nicobar/CLRA/Form XXIII Register of Overtime.xlsx",
    "/Andman Nicobar/CLRA/Form XXIV.xlsx",
    "/Andman Nicobar/FORM 11 Accident Book ESIC.pdf",
    "/Andman Nicobar/FORM 6 Register Of Employees ESIC.xls",
    "/Andman Nicobar/Form A Shop & Esatbilashment.xlsx",
    "/Andman Nicobar/Form C.xlsx",
    "/Andman Nicobar/Form D Holidays.xlsx",
    "/Andman Nicobar/Form E Holiday.xlsx",
    "/Andman Nicobar/Form F Holidays.xlsx",
    "/Andman Nicobar/Form II Wages silp.xlsx",
    "/Andman Nicobar/Form III Muster Rolll.xlsx",
    "/Andman Nicobar/Form IV Overtime.xlsx",
    "/Andman Nicobar/Form V Leave book.xlsx",
    "/Andman Nicobar/Form VI Employee register.xlsx",
    "/Andman Nicobar/FORM XII.xlsx",
    "/Andman Nicobar/Form XIV Annexed To The Rationalisation Of Forms And Reports Under Certain Labour Laws Rules, 2017.xlsx",
  ],
  "Arunchal Pradesh": [
    "/Arunchal Pradesh/CLRA/FORM XII.xlsx",
    "/Arunchal Pradesh/CLRA/FORM XVI Muster Roll.xlsx",
    "/Arunchal Pradesh/download.htm",
    "/Arunchal Pradesh/FORM 11 Accident Book ESIC.pdf",
    "/Arunchal Pradesh/FORM 6 Register Of Employees ESIC.xls",
    "/Arunchal Pradesh/FORM I Register of Fines.xlsx",
    "/Arunchal Pradesh/FORM I.docx",
    "/Arunchal Pradesh/FORM II.xlsx",
    "/Arunchal Pradesh/FORM III Annual Return.xlsx",
    "/Arunchal Pradesh/FORM IV Overtime.xlsx",
    "/Arunchal Pradesh/FORM IV.xlsx",
    "/Arunchal Pradesh/FORM V Muster Roll.xlsx",
    "/Arunchal Pradesh/FORM X Register Of Wages.xlsx",
    "/Arunchal Pradesh/FORM XIV.xlsx",
  ],
  "Assam": [
    "/Assam/BOCW/FORM XIX Fine.XLSX",
    "/Assam/BOCW/FORM XVI Muster.XLSX",
    "/Assam/BOCW/FORM XVII Muster.XLSX",
    "/Assam/BOCW/FORM XVIII Muster.XLSX",
    "/Assam/BOCW/FORM XX Damges.XLSX",
    "/Assam/BOCW/FORM XXI Advance.XLSX",
    "/Assam/BOCW/FORM XXII Overtime.XLSX",
    "/Assam/BOCW/FORM XXIII.XLSX",
    "/Assam/CLRA/Form XIII Reg Workman.docx",
    "/Assam/CLRA/Form XX Fines.docx",
    "/Assam/CLRA/Form XXI Damges.docx",
    "/Assam/CLRA/Form XXII Advance.docx",
    "/Assam/CLRA/Form XXIII Overtime.docx",
    "/Assam/FORM 25 Muster Factories.xlsx",
    "/Assam/Form G Woman Muster.xlsx",
    "/Assam/Form I Fine.xlsx",
    "/Assam/Form I.xlsx",
    "/Assam/Form II Damges.xlsx",
    "/Assam/Form II.xlsx",
    "/Assam/Form III Advance.xlsx",
    "/Assam/Form IV Annual Retrun.xlsx",
    "/Assam/Form IV overtime.xlsx",
    "/Assam/FORM IV-A Wages.xlsx",
    "/Assam/Form V Muster.xlsx",
    "/Assam/Form XVI CLRA Muster.docx",
    "/Assam/Form XVII CLRA Wages.docx",
    "/Assam/PoW Register of wages.xls",
  ],
  "Bihar": [
    "/Bihar/BOCW/Form XIX Fine.xlsx",
    "/Bihar/BOCW/Form XVI Muster.XLSX",
    "/Bihar/BOCW/Form XVII Muster.XLSX",
    "/Bihar/BOCW/Form XVIII Muster.XLSX",
    "/Bihar/BOCW/Form XX Damges.xlsx",
    "/Bihar/BOCW/Form XXI ADavances.XLSX",
    "/Bihar/BOCW/Form XXII Overtime.xlsx",
    "/Bihar/BOCW/Form XXIII.xlsx",
    "/Bihar/CLRA/Form A LWF.xls",
    "/Bihar/CLRA/FORM XII.docx",
    "/Bihar/CLRA/FORM XIII workman.docx",
    "/Bihar/CLRA/FORM XVI.docx",
    "/Bihar/CLRA/FORM XVII.docx",
    "/Bihar/CLRA/FORM XX Fine.docx",
    "/Bihar/CLRA/FORM XXI Damges.docx",
    "/Bihar/CLRA/FORM XXII Advance.docx",
    "/Bihar/CLRA/FORM XXIII.docx",
    "/Bihar/Factories/FORM 10.xlsx",
    "/Bihar/Factories/FORM 15.xlsx",
    "/Bihar/Factories/FORM 22.xlsx",
    "/Bihar/FORM I FIne.docx",
    "/Bihar/FORM I.docx",
    "/Bihar/FORM II Damges.docx",
    "/Bihar/FORM II.docx",
    "/Bihar/FORM III Advance.docx",
    "/Bihar/FORM IV.docx",
    "/Bihar/FORM V Muster roll.docx",
    "/Bihar/FORM VI Wages.docx",
    "/Bihar/FORM X wages.docx",
    "/Bihar/S&E/FORM IX leaves.xlsx",
    "/Bihar/S&E/FORM X Overtime.docx",
    "/Bihar/S&E/FORM XI fines.docx",
  ],
  "Central": [
    "/Central/Apprentices/FORM APPRENTICESHIP 1.docx",
    "/Central/Apprentices/SCHEDULE I-B.docx",
    "/Central/Apprentices/SCHEDULE III FORMAT I.docx",
    "/Central/Apprentices/SCHEDULE IV A.docx",
    "/Central/Apprentices/SCHEDULE IV.docx",
    "/Central/Apprentices/SCHEDULE V.docx",
    "/Central/Apprentices/SCHEDULE VI.docx",
    "/Central/BOCW/Abstract Under Building And Other Construction Workers (Regulation Of Employment And Conditions Of Service) Act, 1996.pdf",
    "/Central/BOCW/FORM I (1).xlsx",
    "/Central/BOCW/FORM I.xlsx",
    "/Central/BOCW/FORM II.xlsx",
    "/Central/BOCW/FORM IV (1).xlsx",
    "/Central/BOCW/FORM IV.xlsx",
    "/Central/BOCW/FORM IX.xlsx",
    "/Central/BOCW/FORM V.xlsx",
    "/Central/BOCW/FORM VI.xlsx",
    "/Central/BOCW/FORM VII.xlsx",
    "/Central/BOCW/FORM VIII.xlsx",
    "/Central/BOCW/FORM XI.xlsx",
    "/Central/BOCW/FORM XII.xlsx",
    "/Central/BOCW/Form XIII Annexed To The Rationalisation Of Forms And Reports Under Certain Labour Laws Rules, 2017.xlsx",
    "/Central/BOCW/FORM XIII.xlsx",
    "/Central/BOCW/Form XIV Annexed To The Rationalisation Of Forms And Reports Under Certain Labour Laws Rules, 2017.xlsx",
    "/Central/BOCW/FORM XIV.xlsx",
    "/Central/BOCW/FORM XIX Fine.XLSX",
    "/Central/BOCW/FORM XV.xlsx",
    "/Central/BOCW/FORM XVI Muster.XLSX",
    "/Central/BOCW/FORM XVII Muster 1.XLSX",
    "/Central/BOCW/FORM XVIII Muster.XLSX",
    "/Central/BOCW/FORM XX Damges.XLSX",
    "/Central/BOCW/FORM XXI Advance.XLSX",
    "/Central/BOCW/FORM XXII Overtime.XLSX",
    "/Central/BOCW/FORM XXIII.XLSX",
    "/Central/BOCW/FORM XXIV.XLSX",
    "/Central/BOCW/FORM XXV.XLSX",
    "/Central/BOCW/FORM XXVI.xlsx",
    "/Central/BOCW/SCHEDULE II.docx",
    "/Central/BOCW/SCHEDULE III First aid box.docx",
    "/Central/BOCW/SCHEDULE IV.docx",
    "/Central/BOCW/SCHEDULE IX.docx",
    "/Central/BOCW/SCHEDULE V.docx",
    "/Central/BOCW/SCHEDULE VIII.docx",
    "/Central/BOCW/SCHEDULE X.docx",
    "/Central/BOCW/SCHEDULE XI.docx",
    "/Central/Bouns/FORM A Computation Of The Allocable Surplus.xlsx",
    "/Central/Bouns/FORM B Set-On And Set-Off Of Allocable Surplus.xlsx",
    "/Central/Bouns/FORM C Bonus Paid To Employees.xlsx",
    "/Central/Bouns/Form D.xlsx",
    "/Central/Child/Abstract of Child Labour Prohibition And Regulation Act 1986.doc",
    "/Central/Child/FORM A.xlsx",
    "/Central/CLRA Central/Abstract Under The Contract Labour (Regulation And Abolition) Act, 1970 (English Version).pdf",
    "/Central/CLRA Central/Abstract Under The Contract Labour (Regulation And Abolition) Act, 1970 (Hindi Version).pdf",
    "/Central/CLRA Central/Form A.xlsx",
    "/Central/CLRA Central/Form B Overtime.xlsx",
    "/Central/CLRA Central/Form B.xlsx",
    "/Central/CLRA Central/Form C.xlsx",
    "/Central/CLRA Central/Form D.xlsx",
    "/Central/CLRA Central/FORM II (1).xlsx",
    "/Central/CLRA Central/FORM II.xlsx",
    "/Central/CLRA Central/FORM III.xlsx",
    "/Central/CLRA Central/FORM VII (1).xlsx",
    "/Central/CLRA Central/FORM VII (2).xlsx",
    "/Central/CLRA Central/FORM VII (3).xlsx",
    "/Central/CLRA Central/FORM VII.xlsx",
    "/Central/CLRA Central/FORM VIII.xlsx",
    "/Central/CLRA Central/FORM XII Register Of Contractors.xlsx",
    "/Central/CLRA Central/FORM XII.xlsx",
    "/Central/CLRA Central/Form XIII Annexed To The Rationalisation Of Forms And Reports Under Certain Labour Laws Rules, 2017.xlsx",
    "/Central/CLRA Central/Form XIII Register of Workmen.xlsx",
    "/Central/CLRA Central/Form XIV Annexed To The Rationalisation Of Forms And Reports Under Certain Labour Laws Rules, 2017.xlsx",
    "/Central/CLRA Central/Form XIX Wage Slip.xlsx",
    "/Central/CLRA Central/Form XVI Muster Roll.xlsx",
    "/Central/CLRA Central/Form XVII Register of Wages.xlsx",
    "/Central/CLRA Central/Form XX Register of Deduction.xlsx",
    "/Central/CLRA Central/Form XXI Register of Fines.xlsx",
    "/Central/CLRA Central/Form XXII Register of Advances.xlsx",
    "/Central/CLRA Central/Form XXIII Register of Overtime.xlsx",
    "/Central/CLRA Central/Form XXIV Half year return.xlsx",
    "/Central/CLRA Central/Form XXV Annual Return.xlsx",
    "/Central/Compensation/FORM A.docx",
    "/Central/Compensation/FORM D.docx",
    "/Central/Compensation/FORM EE.docx",
    "/Central/Compensation/FORM F.docx",
    "/Central/Compensation/Returns As To Compensation.xlsx",
    "/Central/Employent Exchange/FORM ER-1.docx",
    "/Central/Employent Exchange/Notification Of Vacancy.pdf",
    "/Central/ESIC/CA Certificate.pdf",
    "/Central/ESIC/FORM 11.pdf",
    "/Central/ESIC/FORM 6 Register Of Employees.xls",
    "/Central/Exchange/FORM ER II.docx",
    "/Central/Gratuity/Display Of Notice.xlsx",
    "/Central/Gratuity/FORM A Notice Of Opening.xlsx",
    "/Central/Gratuity/FORM B Notice Of Change.xlsx",
    "/Central/Gratuity/FORM C Notice Of Closure.xlsx",
    "/Central/Gratuity/FORM F Nomination Form And Updation Of Nomination Form.xlsx",
    "/Central/Gratuity/FORM G Nomination Form And Updation Of Nomination Form.xlsx",
    "/Central/Gratuity/FORM I Payment Of Gratuity.xlsx",
    "/Central/Gratuity/FORM J Payment Of Gratuity.xlsx",
    "/Central/Gratuity/FORM K Payment Of Gratuity.xlsx",
    "/Central/Gratuity/FORM L Payment Of Gratuity.xlsx",
    "/Central/Gratuity/FORM U Abstract Under Payment Of Gratuity Act, 1972.pdf",
    "/Central/Maternity/FORM A.xlsx",
    "/Central/Maternity/FORM B, C, D, E, F, G, H, I And J.docx",
    "/Central/Maternity/FORM L.xlsx",
    "/Central/Maternity/FORM M.xlsx",
    "/Central/Maternity/FORM N.xlsx",
    "/Central/Maternity/FORM O.xlsx",
    "/Central/Mines/Abstarct Under Mines Act.docx",
    "/Central/Mines/FORM A (1).xlsx",
    "/Central/Mines/FORM A (2).xlsx",
    "/Central/Mines/FORM A.xlsx",
    "/Central/Mines/FORM B.xlsx",
    "/Central/Mines/FORM D.xlsx",
    "/Central/Mines/FORM E (1).xlsx",
    "/Central/Mines/FORM E.xlsx",
    "/Central/Mines/FORM J.xlsx",
    "/Central/Mines/FORM K.xlsx",
    "/Central/Mines/FORM L.xlsx",
    "/Central/Mines/FORM M.xlsx",
    "/Central/Mines/FORM O.xlsx",
    "/Central/Mines/FORM T.xlsx",
    "/Central/PF/Composite Declaration FORM 11.docx",
    "/Central/PF/FORM 2 Nomination And Declaration Form For Unexempted-Exempted Establishments.pdf",
    "/Central/PF/FORM 7(IF).xlsx",
    "/Central/PF/Statement IW-1.xlsx",
    "/Central/Remuration/Form B.xlsx",
    "/Central/Sales Promotion/FORM A.xlsx",
    "/Central/Sales Promotion/FORM B.xlsx",
    "/Central/Sales Promotion/FORM C.xlsx",
    "/Central/Sales Promotion/FORM D.xlsx",
    "/Central/Sales Promotion/FORM E.xlsx",
    "/Central/SEXUAL HARSHMANET/Display Of Order Of IC Constitution And Penal Consequences Of Sexual Harassment.docx",
    "/Central/SEXUAL HARSHMANET/Handbook On Sexual Harassment Of Women At Workplace.pdf",
    "/Central/SEXUAL HARSHMANET/ICC Annual Report Template.docx",
    "/Central/SEXUAL HARSHMANET/ICC Member Acceptance And Confidentiality Agreement.docx",
    "/Central/SEXUAL HARSHMANET/Internal Committe/Order Constituting The ICC.docx",
    "/Central/SEXUAL HARSHMANET/Sample Anti Sexual Harassment Policy.docx",
    "/Central/SEXUAL HARSHMANET/SH Annual Report Format.docx",
    "/Central/Wages/Form B (1).xlsx",
    "/Central/Wages/Form B (2).xlsx",
    "/Central/Wages/FORM B.xlsx",
    "/Central/Wages/FORM C (1).xlsx",
    "/Central/Wages/FORM C (2) Damges.xlsx",
    "/Central/Wages/FORM C (2) Fine.xlsx",
    "/Central/Wages/Form C (2).xlsx",
    "/Central/Wages/FORM C.xlsx",
    "/Central/Wages/Form D (1).xlsx",
    "/Central/Wages/FORM D.xlsx",
    "/Central/Wages/Form I (1).xlsx",
    "/Central/Wages/Form I (2) Air Tranport.xlsx",
    "/Central/Wages/FORM I (2).xlsx",
    "/Central/Wages/Form I Application for Registration.xlsx",
    "/Central/Wages/FORM I.docx",
    "/Central/Wages/Form I.xlsx",
    "/Central/Wages/FORM II.xlsx",
    "/Central/Wages/FORM III Annual Return.xlsx",
    "/Central/Wages/FORM IV.xlsx",
    "/Central/Wages/FORM IX-A Abstract Of The Minimum Wages Act, 1948.docx",
    "/Central/Wages/FORM V master.xlsx",
    "/Central/Wages/FORM VI.xlsx",
    "/Central/Wages/Form VIII.xlsx",
    "/Central/Wages/FORM X.xlsx",
    "/Central/Wages/Form XI Abstract Of The Payment Of Wages Act, 1936 And The Rules.docx",
    "/Central/Wages/FORM XI.docx",
  ],
  "Chandigarh": [
    "/Chandigarh/BOCW/FORM XIX Fine.XLSX",
    "/Chandigarh/BOCW/FORM XVI Muster roll.XLSX",
    "/Chandigarh/BOCW/FORM XVII Muster roll.XLSX",
    "/Chandigarh/BOCW/FORM XVIII Muster roll.XLSX",
    "/Chandigarh/BOCW/FORM XX Damges.XLSX",
    "/Chandigarh/BOCW/FORM XXI Advances.XLSX",
    "/Chandigarh/BOCW/FORM XXII Overtime.XLSX",
    "/Chandigarh/BOCW/FORM XXIII wage.XLSX",
    "/Chandigarh/CLRA/FORM XIII Workman.docx",
    "/Chandigarh/CLRA/FORM XVI Muster roll.docx",
    "/Chandigarh/CLRA/FORM XVII Muster.docx",
    "/Chandigarh/CLRA/FORM XX Fine.docx",
    "/Chandigarh/CLRA/FORM XXI Damges.docx",
    "/Chandigarh/CLRA/FORM XXII Advance.docx",
    "/Chandigarh/CLRA/FORM XXIII Overtime.docx",
    "/Chandigarh/Factories/FORM 25 Muster.xlsx",
    "/Chandigarh/Factories/FORM No. 10.xlsx",
    "/Chandigarh/FORM I Fine.docx",
    "/Chandigarh/FORM II Damges.docx",
    "/Chandigarh/FORM IV Overtine.docx",
    "/Chandigarh/FORM V Minimum wages.docx",
    "/Chandigarh/FORM X.docx",
    "/Chandigarh/S&E/FORM C Empyee.docx",
    "/Chandigarh/S&E/FORM D Wages.docx",
    "/Chandigarh/S&E/FORM E.docx",
  ],
  "Chhattisgarh": [
    "/Chhattisgarh/BOCW/FORM XIX Fine.XLSX",
    "/Chhattisgarh/BOCW/FORM XVI Muster roll.XLSX",
    "/Chhattisgarh/BOCW/FORM XVII Damges.XLSX",
    "/Chhattisgarh/BOCW/FORM XVIII Muster roll.XLSX",
    "/Chhattisgarh/BOCW/FORM XX Damges.XLSX",
    "/Chhattisgarh/BOCW/FORM XXI Advance.XLSX",
    "/Chhattisgarh/BOCW/FORM XXII Overtime.XLSX",
    "/Chhattisgarh/BOCW/FORM XXIII wage.XLSX",
    "/Chhattisgarh/BOCW/FORM XXX Benefisary.xlsx",
    "/Chhattisgarh/BOCW/FORM XXXVII.xlsx",
    "/Chhattisgarh/CLRA/FORM XII Contractor.docx",
    "/Chhattisgarh/CLRA/FORM XVI Muster.docx",
    "/Chhattisgarh/CLRA/FORM XVII Muster.docx",
    "/Chhattisgarh/CLRA/FORM XX Fine.docx",
    "/Chhattisgarh/CLRA/FORM XXI Damges.docx",
    "/Chhattisgarh/CLRA/FORM XXII Adavnce.docx",
    "/Chhattisgarh/Factory/FORM 11.xlsx",
    "/Chhattisgarh/Factory/FORM 33.xlsx",
    "/Chhattisgarh/Factory/FORM 34.xlsx",
    "/Chhattisgarh/Minimum wages/FORM I Fine.docx",
    "/Chhattisgarh/Minimum wages/FORM II Damges.docx",
    "/Chhattisgarh/Minimum wages/FORM IV Overtime.docx",
    "/Chhattisgarh/Minimum wages/FORM V.docx",
    "/Chhattisgarh/Minimum wages/FORM XI.docx",
    "/Chhattisgarh/S&E/FORM  J.docx",
    "/Chhattisgarh/S&E/FORM I.docx",
    "/Chhattisgarh/S&E/FORM K.docx",
    "/Chhattisgarh/S&E/FORM N.docx",
    "/Chhattisgarh/Wages act/FORM I fine.docx",
    "/Chhattisgarh/Wages act/FORM II Damges.docx",
    "/Chhattisgarh/Wages act/FORM III Fine.docx",
    "/Chhattisgarh/Wages act/Register of wages PoW Act.xls",
  ],
  "Dadman Dia": [
    "/Dadman Dia/CLRA/Form XVI Muster Roll.xlsx",
    "/Dadman Dia/CLRA/Form XVII Register of Wages.xlsx",
    "/Dadman Dia/CLRA/Form XX Fine.xlsx",
    "/Dadman Dia/CLRA/Form XXI Register of Fines.xlsx",
    "/Dadman Dia/CLRA/Form XXII Register of Advances.xlsx",
    "/Dadman Dia/CLRA/Form XXIII Register of Overtime.xlsx",
    "/Dadman Dia/Factory/FORM 18.xlsx",
    "/Dadman Dia/Factory/FORM 20.xlsx",
    "/Dadman Dia/Factory/FORM 22.xlsx",
    "/Dadman Dia/Factory/FORM 23.xlsx",
    "/Dadman Dia/Factory/FORM 24.xlsx",
    "/Dadman Dia/Factory/Form 36.xlsx",
    "/Dadman Dia/Factory/Form 37.xlsx",
    "/Dadman Dia/MInimum Wages/Form I Register of Fines.xlsx",
    "/Dadman Dia/MInimum Wages/Form II.xlsx",
    "/Dadman Dia/MInimum Wages/Form IV Overtime Register for Wokers.xlsx",
    "/Dadman Dia/MInimum Wages/Form V Muster Roll.xlsx",
    "/Dadman Dia/MInimum Wages/Form X Register of Wages.xlsx",
    "/Dadman Dia/S& E/Form XII Register of Leave.xlsx",
    "/Dadman Dia/S& E/Form XIII Leave Book.xlsx",
    "/Dadman Dia/S& E/Form XXIII Register of Wages.xlsx",
  ],
  "Dadra & Nagar Heveli": [
    "/Dadra & Nagar Heveli/FORM I Fine.docx",
    "/Dadra & Nagar Heveli/FORM II Damges.docx",
    "/Dadra & Nagar Heveli/FORM III Wages.docx",
    "/Dadra & Nagar Heveli/FORM IV Advance.docx",
    "/Dadra & Nagar Heveli/Goa S& E/FORM XX.xlsx",
    "/Dadra & Nagar Heveli/Goa S& E/FORM XXI.xlsx",
    "/Dadra & Nagar Heveli/Goa S& E/FORM XXII.xlsx",
    "/Dadra & Nagar Heveli/Goa S& E/FORM XXIII.xlsx",
    "/Dadra & Nagar Heveli/Minimum wages/FORM I Fine.xlsx",
    "/Dadra & Nagar Heveli/Minimum wages/FORM II Damgmes.xlsx",
    "/Dadra & Nagar Heveli/Minimum wages/FORM IV Overtime.xlsx",
    "/Dadra & Nagar Heveli/Minimum wages/FORM V Muster.xlsx",
    "/Dadra & Nagar Heveli/Minimum wages/FORM X Wages.xlsx",
  ],
  "Dehli": [
    "/Dehli/BLWF/FORM A.docx",
    "/Dehli/BLWF/FORM D.docx",
    "/Dehli/BOCW/FORM A Woman workar.xlsx",
    "/Dehli/BOCW/FORM XIX Fine.XLSX",
    "/Dehli/BOCW/FORM XVI Muster.XLSX",
    "/Dehli/BOCW/FORM XVII Muster.XLSX",
    "/Dehli/BOCW/FORM XVIII Muster.XLSX",
    "/Dehli/BOCW/FORM XX Damges.XLSX",
    "/Dehli/BOCW/FORM XXI Advance.XLSX",
    "/Dehli/BOCW/FORM XXII overtime.XLSX",
    "/Dehli/BOCW/FORM XXIII Wage.XLSX",
    "/Dehli/CLRA/FORM XVI  Muster.docx",
    "/Dehli/CLRA/FORM XVII Muster.docx",
    "/Dehli/CLRA/FORM XX  Fine.docx",
    "/Dehli/CLRA/FORM XXI Damges.docx",
    "/Dehli/CLRA/FORM XXII Advance.docx",
    "/Dehli/CLRA/FORM XXIII Overtime.docx",
    "/Dehli/Factory/FORM 10 overtime.xlsx",
    "/Dehli/Factory/FORM 11(a) Child.xlsx",
    "/Dehli/Factory/FORM 11(b) Child.xlsx",
    "/Dehli/Factory/FORM 12 Audilt.xlsx",
    "/Dehli/Factory/FORM 13 child.xlsx",
    "/Dehli/Factory/FORM 14 Child.xlsx",
    "/Dehli/Factory/FORM 15.xlsx",
    "/Dehli/Factory/FORM 16.xlsx",
    "/Dehli/Factory/FORM 17.xlsx",
    "/Dehli/Factory/FORM 26.xlsx",
    "/Dehli/Factory/FORM 27.xlsx",
    "/Dehli/Form A Muster Roll Workman.xlsx",
    "/Dehli/Minimum Wages/FORM I.docx",
    "/Dehli/Minimum Wages/FORM II.docx",
    "/Dehli/Minimum Wages/FORM IV.docx",
    "/Dehli/Minimum Wages/FORM V.docx",
    "/Dehli/Minimum Wages/FORM X.docx",
  ],
  "Goa": [
    "/Goa/BOCW/FORM XIX Fine.XLSX",
    "/Goa/BOCW/FORM XVI muster.XLSX",
    "/Goa/BOCW/FORM XVII Muster.XLSX",
    "/Goa/BOCW/FORM XVIII Muster.XLSX",
    "/Goa/BOCW/FORM XX Damges.XLSX",
    "/Goa/BOCW/FORM XXI Advance.XLSX",
    "/Goa/BOCW/FORM XXII Overtime.XLSX",
    "/Goa/CLRA/FORM IX Workman.xlsx",
    "/Goa/CLRA/FORM XII.xlsx",
    "/Goa/CLRA/FORM XIII.xlsx",
    "/Goa/CLRA/FORM XIV (1) Overtime.xlsx",
    "/Goa/CLRA/FORM XIV.xlsx",
    "/Goa/CLRA/FORM XVI Fine.xlsx",
    "/Goa/CLRA/FORM XVII Damges.xlsx",
    "/Goa/CLRA/FORM XVIII Advance.xlsx",
    "/Goa/Factory/FORM 10 Machiner worker.xlsx",
    "/Goa/Factory/FORM 18 OVertime.xlsx",
    "/Goa/Factory/FORM 20 Aludt.xlsx",
    "/Goa/Factory/FORM 22 Child.xlsx",
    "/Goa/Factory/FORM 23.xlsx",
    "/Goa/Factory/FORM 24 Leave Book.xlsx",
    "/Goa/Factory/Form 36 Muster Roll.xlsx",
    "/Goa/Minimum wages/FORM I Fine.xlsx",
    "/Goa/Minimum wages/FORM II Damges.xlsx",
    "/Goa/Minimum wages/FORM VIII Ovvertime.xlsx",
    "/Goa/Minimum wages/FORM X wages.xlsx",
    "/Goa/Minimum wages/FORM XI muste.xlsx",
    "/Goa/Minimum wages/FORM XII Muster.xlsx",
    "/Goa/S& E/FORM XII Leave.xlsx",
    "/Goa/S& E/FORM XIII Leave book.xlsx",
    "/Goa/S& E/FORM XX Employment.xlsx",
    "/Goa/S& E/FORM XXI.xlsx",
    "/Goa/S& E/FORM XXII.xlsx",
    "/Goa/S& E/FORM XXIII.xlsx",
  ],
  "Gujrat": [
    "/Gujrat/BOCW/FORM A.xlsx",
    "/Gujrat/BOCW/FORM B (1) Muster.xlsx",
    "/Gujrat/BOCW/FORM B.xlsx",
    "/Gujrat/BOCW/FORM C Fine Damges.xlsx",
    "/Gujrat/BOCW/FORM D Muster.xlsx",
    "/Gujrat/CLRA/FORM A Workman reg.xlsx",
    "/Gujrat/CLRA/FORM B Muster.xlsx",
    "/Gujrat/CLRA/FORM B Overtime.xlsx",
    "/Gujrat/CLRA/FORM C Fine.xlsx",
    "/Gujrat/CLRA/FORM D Muster.xlsx",
    "/Gujrat/Factory/FORM A Register Of Wages.docx",
    "/Gujrat/Factory/FORM No. 15.xlsx",
    "/Gujrat/Factory/FORM NO. 9.xlsx",
    "/Gujrat/Factory/FORM NO.10.xlsx",
    "/Gujrat/Factory/FORM NO.13.xlsx",
    "/Gujrat/Factory/FORM NO.8.xlsx",
    "/Gujrat/LWF/FORM A-1.docx",
    "/Gujrat/Minimum wages/FORM B Overtime.xlsx",
    "/Gujrat/Minimum wages/FORM B Wages register.xlsx",
    "/Gujrat/Minimum wages/FORM C Fine.xlsx",
    "/Gujrat/Minimum wages/FORM D Muster.xlsx",
    "/Gujrat/Minimum wages/FORM IV-B Wage Slip.docx",
    "/Gujrat/S&E/FORM A Muster Roll Woman Worker.docx",
    "/Gujrat/S&E/FORM I.docx",
    "/Gujrat/S&E/FORM J.docx",
    "/Gujrat/S&E/FORM M Register Of Leave.docx",
    "/Gujrat/S&E/FORM N Leave book.xlsx",
    "/Gujrat/S&E/FORM P Muster.xlsx",
    "/Gujrat/Wages Act/FORM B Wages.xlsx",
    "/Gujrat/Wages Act/FORM C Advance.xlsx",
    "/Gujrat/Wages Act/FORM C Damges.xlsx",
    "/Gujrat/Wages Act/FORM C Fine.xlsx",
  ],
  "Hariyana": [
    "/Hariyana/BOCW/FORM XXIX.xlsx",
    "/Hariyana/BOCW/FORM XXV.xlsx",
    "/Hariyana/BOCW/FORM XXVI Muster.xlsx",
    "/Hariyana/BOCW/FORM XXVII Muster.xlsx",
    "/Hariyana/BOCW/FORM XXVIII Muster.xlsx",
    "/Hariyana/BOCW/FORM XXX.xlsx",
    "/Hariyana/BOCW/FORM XXXI.XLSX",
    "/Hariyana/BOCW/FORM XXXII.xlsx",
    "/Hariyana/BOCW/FORM XXXIII.xlsx",
    "/Hariyana/CLRA/FORM 13 Register Of Wages.xlsx",
    "/Hariyana/CLRA/FORM 8 Register Of Particulars Of Contractors.docx",
    "/Hariyana/CLRA/FORM IX Register Of Workmen Employed By Contractor.xls",
    "/Hariyana/CLRA/FORM XII Muster Roll.xlsx",
    "/Hariyana/CLRA/FORM XIX Register Of Overtime.xlsx",
    "/Hariyana/CLRA/FORM XVI Register Of Deduction For Damage Or Loss.xls",
    "/Hariyana/CLRA/FORM XVII Register Of Fines.xls",
    "/Hariyana/CLRA/FORM XVIII Register Of Advance.xls",
    "/Hariyana/Factory/FORM No. 12.xlsx",
    "/Hariyana/Factory/FORM No. 15.xlsx",
    "/Hariyana/Factory/FORM No. 37.xlsx",
    "/Hariyana/Factory/FORM No. 7-A.xlsx",
    "/Hariyana/FORM A Muster Roll Woman Worker.pdf",
    "/Hariyana/LWF/Form A.xls",
    "/Hariyana/Minimum wages/FORM IV Overtime Register For Workers.docx",
    "/Hariyana/Minimum wages/FORM X (1) Fine.xlsx",
    "/Hariyana/Minimum wages/FORM X.xlsx",
    "/Hariyana/PoW/FORM VI Fine.xlsx",
    "/Hariyana/PoW/PoW Register of wages.xls",
    "/Hariyana/S&E/FORM B Register Of Fines Realised And Unpaid.docx",
    "/Hariyana/S&E/FORM C Register Of Employees.docx",
    "/Hariyana/S&E/FORM D Register Of Wages Of Employees.docx",
    "/Hariyana/S&E/FORM E Register Of Deductions.docx",
  ],
  "Himachal pradesh": [
    "/Himachal pradesh/BOCW/Form XIX Fine.xlsx",
    "/Himachal pradesh/BOCW/Form XV.xlsx",
    "/Himachal pradesh/BOCW/Form XVI.XLSX",
    "/Himachal pradesh/BOCW/Form XVII Muster.XLSX",
    "/Himachal pradesh/BOCW/Form XVIII Muster.XLSX",
    "/Himachal pradesh/BOCW/Form XX Damges.xlsx",
    "/Himachal pradesh/BOCW/Form XXI Advance.XLSX",
    "/Himachal pradesh/BOCW/Form XXII Overtime.xlsx",
    "/Himachal pradesh/BOCW/Form XXIII.xlsx",
    "/Himachal pradesh/BOCW/Form XXVI.xlsx",
    "/Himachal pradesh/CLRA/Form XII.xlsx",
    "/Himachal pradesh/CLRA/Form XIII.xlsx",
    "/Himachal pradesh/CLRA/Form XIX.xlsx",
    "/Himachal pradesh/CLRA/Form XVI Muster Roll.xlsx",
    "/Himachal pradesh/CLRA/Form XVII Rate Of Wages.xlsx",
    "/Himachal pradesh/CLRA/Form XX.xlsx",
    "/Himachal pradesh/CLRA/Form XXI Register of Fines.xlsx",
    "/Himachal pradesh/CLRA/Form XXII Register Of Advances.xlsx",
    "/Himachal pradesh/CLRA/Form XXIII Register of OverTime.xlsx",
    "/Himachal pradesh/Factory/Form 10 Overtime Muster Roll for Exempted Workers.xlsx",
    "/Himachal pradesh/Factory/Form 12 Register of Adult Workers.xlsx",
    "/Himachal pradesh/Factory/Form 14 Register of Child Workers.xlsx",
    "/Himachal pradesh/Factory/Form 15 Register of Leave with Wages.xlsx",
    "/Himachal pradesh/Factory/Form 16 Leave Book.xlsx",
    "/Himachal pradesh/Factory/Form 25 Muster Roll.xlsx",
    "/Himachal pradesh/MInimum wages/Form I Fine.xlsx",
    "/Himachal pradesh/MInimum wages/Form II Damges.xlsx",
    "/Himachal pradesh/MInimum wages/Form V OVertime.xlsx",
    "/Himachal pradesh/MInimum wages/Form VI.xlsx",
    "/Himachal pradesh/MInimum wages/Form VII.xlsx",
    "/Himachal pradesh/POW/Form I Register of Fines.xlsx",
    "/Himachal pradesh/POW/Form II Register of Deductions.xlsx",
    "/Himachal pradesh/POW/Form III Register of Advances.xlsx",
    "/Himachal pradesh/S&E/Form 10 Duduction.xlsx",
    "/Himachal pradesh/S&E/Form 11.xlsx",
    "/Himachal pradesh/S&E/Form 8.xlsx",
    "/Himachal pradesh/S&E/Form 9.xlsx",
  ],
  "Jammu Kashmir": [
    "/Jammu Kashmir/BOCW/FORM XIX Fine.XLSX",
    "/Jammu Kashmir/BOCW/FORM XV.xlsx",
    "/Jammu Kashmir/BOCW/FORM XVI Muster.XLSX",
    "/Jammu Kashmir/BOCW/FORM XVII Muster.XLSX",
    "/Jammu Kashmir/BOCW/FORM XVIII Muster.XLSX",
    "/Jammu Kashmir/BOCW/FORM XX Damges.XLSX",
    "/Jammu Kashmir/BOCW/FORM XXI avance s.XLSX",
    "/Jammu Kashmir/BOCW/FORM XXII Overtime.XLSX",
    "/Jammu Kashmir/BOCW/FORM XXIII.XLSX",
    "/Jammu Kashmir/BOCW/FORM XXVI.xlsx",
    "/Jammu Kashmir/CLRA/Form XII.xlsx",
    "/Jammu Kashmir/CLRA/Form XIII.xlsx",
    "/Jammu Kashmir/CLRA/Form XVI Muster Roll.xlsx",
    "/Jammu Kashmir/CLRA/Form XVII Register Of Wages.xlsx",
    "/Jammu Kashmir/CLRA/Form XX Fine.xlsx",
    "/Jammu Kashmir/CLRA/Form XXI Register of Fines.xlsx",
    "/Jammu Kashmir/CLRA/Form XXII Register Of Advances.xlsx",
    "/Jammu Kashmir/CLRA/Form XXIII Register of OverTime.xlsx",
    "/Jammu Kashmir/Factory/Form 11 Overtime Muster Roll for Exempted Workers.xlsx",
    "/Jammu Kashmir/Factory/Form 13 Register of Adult Workers.xlsx",
    "/Jammu Kashmir/Factory/Form 15 Register of Child Workers.xlsx",
    "/Jammu Kashmir/Factory/Form 16 Register of Leave Wages.xlsx",
    "/Jammu Kashmir/Factory/Form 17 Leave Book.xlsx",
    "/Jammu Kashmir/Factory/Form 26 Muster Roll.xlsx",
    "/Jammu Kashmir/MInimum wages/FORM I Fine.xlsx",
    "/Jammu Kashmir/MInimum wages/FORM IV Overtime.xlsx",
    "/Jammu Kashmir/MInimum wages/FORM IV Wages.xlsx",
    "/Jammu Kashmir/MInimum wages/FORM V Muster.xlsx",
    "/Jammu Kashmir/POw/Form A Muster for Woman worker.xlsx",
    "/Jammu Kashmir/POw/FORM I Advance.xlsx",
    "/Jammu Kashmir/POw/FORM I Damges.xlsx",
    "/Jammu Kashmir/POw/FORM I Fine.xlsx",
    "/Jammu Kashmir/POw/FORM II Wages.xlsx",
    "/Jammu Kashmir/POw/FORM XI Attendance.xlsx",
    "/Jammu Kashmir/S&E/FORM G Leave register.xlsx",
    "/Jammu Kashmir/S&E/FORM H Leave book.xlsx",
    "/Jammu Kashmir/S&E/FORM L Employment.xlsx",
  ],
  "Jharkhand": [
    "/Jharkhand/CLRA/FORM XII Contractor.docx",
    "/Jharkhand/CLRA/FORM XIII Workmen.docx",
    "/Jharkhand/CLRA/FORM XVI.docx",
    "/Jharkhand/CLRA/FORM XVII.docx",
    "/Jharkhand/CLRA/FORM XX Fine.docx",
    "/Jharkhand/CLRA/FORM XXI Damges.docx",
    "/Jharkhand/CLRA/FORM XXII Advance.docx",
    "/Jharkhand/CLRA/FORM XXIII Overtime.docx",
    "/Jharkhand/Factory/FORM 12 Audlt.xlsx",
    "/Jharkhand/Factory/FORM 14 Child.xlsx",
    "/Jharkhand/Factory/FORM 32.xlsx",
    "/Jharkhand/Factory/FORM No. 10.xlsx",
    "/Jharkhand/Factory/FORM No. 15 Leave.xlsx",
    "/Jharkhand/Factory/FORM No.10A Overtime.xlsx",
    "/Jharkhand/FORM 6 Register Of Employees ESIC.xls",
    "/Jharkhand/FORM A Child.docx",
    "/Jharkhand/FORM A Woman worker.docx",
    "/Jharkhand/Minimum wages/FORM I Fine.docx",
    "/Jharkhand/Minimum wages/FORM II Damges.docx",
    "/Jharkhand/Minimum wages/FORM IV Overtime.docx",
    "/Jharkhand/Minimum wages/FORM V.docx",
    "/Jharkhand/Minimum wages/FORM X Wages.docx",
    "/Jharkhand/Pow/FORM I Fine.docx",
    "/Jharkhand/Pow/FORM II Damges.docx",
    "/Jharkhand/Pow/FORM III.docx",
    "/Jharkhand/Pow/FORM VI.docx",
    "/Jharkhand/S&E/FORM IX Leave.docx",
    "/Jharkhand/S&E/FORM X Overtime.docx",
    "/Jharkhand/S&E/FORM XI Fine.docx",
  ],
  "KARNATKA": [
    "/KARNATKA/BOCW/FORM XL Fine.xlsx",
    "/KARNATKA/BOCW/FORM XLI Damges.xlsx",
    "/KARNATKA/BOCW/FORM XLII Overtime.xlsx",
    "/KARNATKA/BOCW/FORM XLIII Wage book.xlsx",
    "/KARNATKA/BOCW/FORM XXV.xlsx",
    "/KARNATKA/BOCW/FORM XXXI.xlsx",
    "/KARNATKA/BOCW/FORM XXXIX Advance.xlsx",
    "/KARNATKA/BOCW/FORM XXXV.xlsx",
    "/KARNATKA/BOCW/FORM XXXVI Muster.xlsx",
    "/KARNATKA/BOCW/FORM XXXVII Muster.xlsx",
    "/KARNATKA/BOCW/FORM XXXVIII Muster.xlsx",
    "/KARNATKA/CLRA/FORM T Combined Muster Roll And Wage Register.xls (1).xlsx",
    "/KARNATKA/CLRA/FORM T Combined Muster Roll And Wage Register.xls (2).xlsx",
    "/KARNATKA/CLRA/FORM T Combined Muster Roll And Wage Register.xls (3).xlsx",
    "/KARNATKA/CLRA/FORM T Combined Muster Roll And Wage Register.xls (4).xlsx",
    "/KARNATKA/CLRA/FORM T Combined Muster Roll And Wage Register.xls.xlsx",
    "/KARNATKA/CLRA/FORM XII Contractor.docx",
    "/KARNATKA/CLRA/FORM XIX Wage Slip.docx",
    "/KARNATKA/CLRA/FORM XVI Muster.docx",
    "/KARNATKA/CLRA/FORM XVII.docx",
    "/KARNATKA/CLRA/FORM XX.docx",
    "/KARNATKA/CLRA/FORM XXII.docx",
    "/KARNATKA/CLRA/FORM XXIII Overtime.docx",
    "/KARNATKA/CLRA/FORMXIII Workmen.docx",
    "/KARNATKA/Factory/FORM 9 Register Of Overtime And Payment.docx",
    "/KARNATKA/Factory/FORM No. 11 Register Of Adult Workers (1).docx",
    "/KARNATKA/Factory/FORM No. 11 Register Of Adult Workers.docx",
    "/KARNATKA/Factory/FORM No. 13 Register Of Child Workers.docx",
    "/KARNATKA/Factory/FORM No. 14 Register Of Leave With Wages.docx",
    "/KARNATKA/Factory/FORM No. 15 Leave Book.docx",
    "/KARNATKA/Factory/FORM No. 22 Muster Roll Cum Wage Register.docx",
    "/KARNATKA/Factory/FORM No. 22 Wage Register Cum Muster Roll.xlsx",
    "/KARNATKA/Factory/FORM No. 23 Register Of Accidents And Dangerous Occurrences.docx",
    "/KARNATKA/Factory/FORM No. 30.docx",
    "/KARNATKA/Factory/FORM No. 31 Prescribed For Report Of Examination Of Hoist Or Lift.docx",
    "/KARNATKA/Factory/FORM No. 32 Prescribed For Report Of Examination For Cranes And Other Lifting Machines.docx",
    "/KARNATKA/Factory/FORM No. 33 Register Of Tight Fitting Clothing.docx",
    "/KARNATKA/Factory/FORM No. 4 Certificate Of Fitness.docx",
    "/KARNATKA/Factory/FORM No. 40 Sickness, Absenteeism Register.docx",
    "/KARNATKA/Factory/FORM No. 8 Register Of Compensatory Holidays.docx",
    "/KARNATKA/FORM 5-A PT.docx",
    "/KARNATKA/FORM 6 Register Of Employees ESIC.xls",
    "/KARNATKA/FORM 9-A PT.docx",
    "/KARNATKA/FORM A Register Of Wages KLWF.xlsx",
    "/KARNATKA/FORM A Register Of Wages LWF.xlsx",
    "/KARNATKA/FORM A woman worker.docx",
    "/KARNATKA/FORM B Register Of Fines And Unpaid Accumulations KLWF.xls",
    "/KARNATKA/FORM B Register Of Fines And Unpaid Accumulations LWF.xls",
    "/KARNATKA/FORM D KLWF.docx",
    "/KARNATKA/FORM D LWF.docx",
    "/KARNATKA/FORM T Combined Muster Roll And Wage Register KLWF.xls",
    "/KARNATKA/FORM T Combined Muster Roll And Wage Register LWF.xls",
    "/KARNATKA/Interstate migrant/Form XII Contractor.xlsx",
    "/KARNATKA/Interstate migrant/Form XIII Register emply.xlsx",
    "/KARNATKA/Interstate migrant/Form XIX Fine.xlsx",
    "/KARNATKA/Interstate migrant/Form XV.xlsx",
    "/KARNATKA/Interstate migrant/Form XVI.xlsx",
    "/KARNATKA/Interstate migrant/Form XVII Muster.xlsx",
    "/KARNATKA/Interstate migrant/Form XXII overtime.xlsx",
    "/KARNATKA/Minimum wages/FORM I Fine.docx",
    "/KARNATKA/Minimum wages/FORM II Damges.docx",
    "/KARNATKA/Minimum wages/FORM IV Overtime.docx",
    "/KARNATKA/Minimum wages/FORM T (1) Overtime wages.xlsx",
    "/KARNATKA/Minimum wages/FORM T Muster.xlsx",
    "/KARNATKA/Minimum wages/FORM T.xlsx",
    "/KARNATKA/Minimum wages/FORM VII muster.docx",
    "/KARNATKA/Pow/FORM I Fine Damges.docx",
    "/KARNATKA/Pow/FORM T Fine damges advance.xlsx",
    "/KARNATKA/Pow/FORM T Wages.xlsx",
    "/KARNATKA/S&E/FORM F Register Of Leave With  Wages.docx.xlsx",
    "/KARNATKA/S&E/FORM T Combined Muster Roll And Wage Register.xls",
    "/KARNATKA/S&E/FORM T Combined Muster Roll And Wage Register.xls.xlsx",
  ],
  "Kerala": [
    "/Kerala/BOCW/Form XIX Fine.xlsx",
    "/Kerala/BOCW/Form XV.xlsx",
    "/Kerala/BOCW/Form XVI Muster.xlsx",
    "/Kerala/BOCW/Form XVII Register wages.xlsx",
    "/Kerala/BOCW/Form XVIII Muster.xlsx",
    "/Kerala/BOCW/Form XX Damges.xlsx",
    "/Kerala/BOCW/Form XXI Advane.xlsx",
    "/Kerala/BOCW/Form XXII Overtime.xlsx",
    "/Kerala/BOCW/Form XXIII wage.xlsx",
    "/Kerala/CLRA/FORM XII Contractor.docx",
    "/Kerala/CLRA/FORM XIII workmen.docx",
    "/Kerala/CLRA/FORM XX Fine.docx",
    "/Kerala/CLRA/FORM XXI Damges.docx",
    "/Kerala/CLRA/FORM XXII Damges.docx",
    "/Kerala/CLRA/FORM XXIII OVertime.docx",
    "/Kerala/Factory/FORM 10 Overtime muster.xlsx",
    "/Kerala/Factory/FORM 12 Adult.xlsx",
    "/Kerala/Factory/FORM 14 Child.xlsx",
    "/Kerala/Factory/FORM 15 Leave.xlsx",
    "/Kerala/Factory/FORM 16 Leave book.xlsx",
    "/Kerala/Factory/FORM 17.xlsx",
    "/Kerala/Factory/FORM 25 muster.xlsx",
    "/Kerala/Factory/FORM 29.xlsx",
    "/Kerala/Factory/FORM 41.xlsx",
    "/Kerala/FORM 6 Register Of Employees ESIC.xls",
    "/Kerala/FORM A Woman worker.docx",
    "/Kerala/FORM B LWF.xlsx",
    "/Kerala/FORM C LWF.xlsx",
    "/Kerala/FORM VI Industrial establishment.docx",
    "/Kerala/LWF/FORM A (1).xlsx",
    "/Kerala/Minimum wages/FORM I Damges.docx",
    "/Kerala/Minimum wages/FORM II Fine.docx",
    "/Kerala/Minimum wages/FORM V OVertime.docx",
    "/Kerala/Minimum wages/FORM VI Muster.docx",
    "/Kerala/Minimum wages/FORM XI Wages.docx",
    "/Kerala/Minimum wages/FORM XII wages.docx",
    "/Kerala/Minimum wages/FORM XIV.xlsx",
    "/Kerala/PoW/FORM I.docx",
    "/Kerala/PoW/FORM II.docx",
    "/Kerala/PoW/FORM III.docx",
    "/Kerala/PoW/PoW Register of wages.xls",
    "/Kerala/S&E/FORM A.xlsx",
    "/Kerala/S&E/FORM B.xlsx",
    "/Kerala/S&E/FORM BB.docx",
    "/Kerala/S&E/FORM C.docx",
    "/Kerala/S&E/FORM D.xlsx",
    "/Kerala/S&E/FORM F.docx",
  ],
  "Ladakh": [
  ],
  "Madhya Pradesh": [
    "/Madhya Pradesh/BOCW/FORM XIX Fine.XLSX",
    "/Madhya Pradesh/BOCW/FORM XV (1).xlsx",
    "/Madhya Pradesh/BOCW/FORM XV.XLSX",
    "/Madhya Pradesh/BOCW/FORM XVI Muster.XLSX",
    "/Madhya Pradesh/BOCW/FORM XVII Wages register.XLSX",
    "/Madhya Pradesh/BOCW/FORM XVIII Muster.XLSX",
    "/Madhya Pradesh/BOCW/FORM XX Damges.XLSX",
    "/Madhya Pradesh/BOCW/FORM XXI Advance.XLSX",
    "/Madhya Pradesh/BOCW/FORM XXII Overtime.XLSX",
    "/Madhya Pradesh/BOCW/FORM XXIII.XLSX",
    "/Madhya Pradesh/BOCW/FORM XXVI.xlsx",
    "/Madhya Pradesh/BOCW/FORM XXXVII.XLSX",
    "/Madhya Pradesh/CLRA/FORM XII Contractor.docx",
    "/Madhya Pradesh/CLRA/FORM XIII.docx",
    "/Madhya Pradesh/CLRA/FORM XVI.docx",
    "/Madhya Pradesh/CLRA/FORM XVII.docx",
    "/Madhya Pradesh/CLRA/FORM XX Fine.docx",
    "/Madhya Pradesh/CLRA/FORM XXI Damges.docx",
    "/Madhya Pradesh/CLRA/FORM XXII Advance.docx",
    "/Madhya Pradesh/CLRA/FORM XXIII OVertime.docx",
    "/Madhya Pradesh/Factory/Form 11 Register of Overtime for Exempted Workers.xlsx",
    "/Madhya Pradesh/Factory/FORM 14 Register of Adult Workers (1).xlsx",
    "/Madhya Pradesh/Factory/FORM 14 Register of Adult Workers.xlsx",
    "/Madhya Pradesh/Factory/FORM 17 Register of Child Workers (1).xlsx",
    "/Madhya Pradesh/Factory/FORM 17 Register of Child Workers.xlsx",
    "/Madhya Pradesh/Factory/FORM 18 Register of Leave with Wages.xlsx",
    "/Madhya Pradesh/Factory/FORM 19 Leave Card.xlsx",
    "/Madhya Pradesh/Factory/FORM 21 Health Register.xlsx",
    "/Madhya Pradesh/Factory/FORM 34 Register Of Workers And Tight Fitting Clothing.xlsx",
    "/Madhya Pradesh/FORM 6 Register Of Employees ESIC.xls",
    "/Madhya Pradesh/Minimum wages/FORM A Woman woker.docx",
    "/Madhya Pradesh/Minimum wages/FORM I Fine.docx",
    "/Madhya Pradesh/Minimum wages/FORM II Damges.docx",
    "/Madhya Pradesh/Minimum wages/FORM IV OVertime.docx",
    "/Madhya Pradesh/Minimum wages/FORM V Muster.docx",
    "/Madhya Pradesh/Minimum wages/FORM XI Wages.docx",
    "/Madhya Pradesh/Minimum wages/FORM XIV.docx",
    "/Madhya Pradesh/Pow/FORM A LWF.docx",
    "/Madhya Pradesh/Pow/FORM I Fine.docx",
    "/Madhya Pradesh/Pow/FORM II Damges ].docx",
    "/Madhya Pradesh/Pow/FORM III.docx",
    "/Madhya Pradesh/Pow/Register of Wages_Madhyra Pradesh-POW Rules.xls",
    "/Madhya Pradesh/S&E/FORM I Leave.docx",
    "/Madhya Pradesh/S&E/FORM J Leave Book.docx",
    "/Madhya Pradesh/S&E/FORM K.docx",
    "/Madhya Pradesh/S&E/FORM N Overtime.docx",
  ],
  "MAHARASHTRA": [
    "/MAHARASHTRA/Allowances/FORM A Register Of House Rent Allowance.docx",
    "/MAHARASHTRA/Allowances/FORM I Register Of Workmen.docx",
    "/MAHARASHTRA/BOCW/FORM IX.xlsx",
    "/MAHARASHTRA/BOCW/FORM X Muster.xlsx",
    "/MAHARASHTRA/BOCW/FORM XI Muster.xlsx",
    "/MAHARASHTRA/BOCW/FORM XII Muster.xlsx",
    "/MAHARASHTRA/BOCW/FORM XIII Fine.xlsx",
    "/MAHARASHTRA/BOCW/FORM XIV Damges.xlsx",
    "/MAHARASHTRA/BOCW/FORM XV advance.xlsx",
    "/MAHARASHTRA/BOCW/FORM XVI overtime.xlsx",
    "/MAHARASHTRA/BOCW/FORM XVII wage book.xlsx",
    "/MAHARASHTRA/CLRA/FORM II Attendance Card Cum Wages Slip.xlsx",
    "/MAHARASHTRA/CLRA/FORM II Muster Roll Cum Wage Register.xlsx",
    "/MAHARASHTRA/CLRA/FORM No. 7 Pre employement.xlsx",
    "/MAHARASHTRA/CLRA/FORM VIII Register Of Particulars Of Contractors.docx",
    "/MAHARASHTRA/CLRA/FORM X Identity Card.docx",
    "/MAHARASHTRA/CLRA/FORM XIII Register Of Workmen Employed By Contractor.docx",
    "/MAHARASHTRA/CLRA/FORM XIV Employment Card.docx",
    "/MAHARASHTRA/CLRA/FORM XXIV Return To Be Sent By The Contractor To The Licensing Officer.docx",
    "/MAHARASHTRA/Factory/FORM 17.xlsx",
    "/MAHARASHTRA/Factory/FORM No. 10.xlsx",
    "/MAHARASHTRA/Factory/FORM No. 20.xlsx",
    "/MAHARASHTRA/Factory/FORM No. 29.xlsx",
    "/MAHARASHTRA/Factory/FORM No. 30 accident.xlsx",
    "/MAHARASHTRA/Factory/FORM No.11.xlsx",
    "/MAHARASHTRA/FORM 10 Maternity Benefit Register.docx",
    "/MAHARASHTRA/FORM 6 Register Of Employees ESIC.xls",
    "/MAHARASHTRA/FORM A-1 LWF.xls",
    "/MAHARASHTRA/FORM B Child labour act.docx",
    "/MAHARASHTRA/FORM B Register Of Wages LWF.docx",
    "/MAHARASHTRA/FORM C Register Of Fines And Unpaid Accumulations LWF.xlsx",
    "/MAHARASHTRA/Form II Muster Roll Cum Wages Register LWF.docx",
    "/MAHARASHTRA/Form III B.xlsx",
    "/MAHARASHTRA/Gartuity/FORM I Application For Gratuity By An Employee.docx",
    "/MAHARASHTRA/Gartuity/FORM J Application For Gratuity By A Nominee.docx",
    "/MAHARASHTRA/Gartuity/FORM K Application For Gratuity By A Legal Heir.docx",
    "/MAHARASHTRA/Gartuity/FORM L Notice For Payment Of Gratuity.docx",
    "/MAHARASHTRA/Gartuity/Form U Abstract Under The Payment Of Gratuity Act, 1972.pdf",
    "/MAHARASHTRA/Gartuity/Form U Abstract Under The Payment Of Gratuity Act,1972 (Marathi Version).pdf",
    "/MAHARASHTRA/Maternity/FORM 1.docx",
    "/MAHARASHTRA/Maternity/FORM 2.docx",
    "/MAHARASHTRA/Maternity/FORM 3.docx",
    "/MAHARASHTRA/Maternity/FORM 4.docx",
    "/MAHARASHTRA/Maternity/FORM 5.docx",
    "/MAHARASHTRA/Maternity/FORM 6.docx",
    "/MAHARASHTRA/Maternity/FORM 7.docx",
    "/MAHARASHTRA/Maternity/FORM 8.docx",
    "/MAHARASHTRA/MInimum wages/FORM II Muster Roll Cum Wage Register.xlsx",
    "/MAHARASHTRA/POw/FORM IV Register Of Advances Made To Employed Persons.docx",
    "/MAHARASHTRA/S&E/FORM H Register Of Employment.xlsx",
    "/MAHARASHTRA/S&E/FORM I.docx",
    "/MAHARASHTRA/S&E/FORM II Muster Roll Cum Wage Register.xlsx",
    "/MAHARASHTRA/S&E/FORM J Register Of Employment.docx",
    "/MAHARASHTRA/S&E/FORM K.docx",
    "/MAHARASHTRA/S&E/FORM M.xlsx",
    "/MAHARASHTRA/S&E/FORM O Leave Book.xlsx",
    "/MAHARASHTRA/S&E/FORM P.xlsx",
    "/MAHARASHTRA/S&E/FORM Q Muster.xlsx",
    "/MAHARASHTRA/S&E/FORM-R Annual retrun.XLSX",
  ],
  "Manipur": [
    "/Manipur/CLRA/FORM XII Contractor.xlsx",
    "/Manipur/CLRA/FORM XIII.xlsx",
    "/Manipur/CLRA/FORM XIV.xlsx",
    "/Manipur/CLRA/FORM XIX.xlsx",
    "/Manipur/CLRA/FORM XVI Muster Roll.xlsx",
    "/Manipur/CLRA/FORM XVII Register Of Wages.xlsx",
    "/Manipur/CLRA/FORM XX Fine.xlsx",
    "/Manipur/CLRA/FORM XXI Register of Fines.xlsx",
    "/Manipur/CLRA/FORM XXII ROA.xlsx",
    "/Manipur/CLRA/FORM XXIII Register of OverTime.xlsx",
    "/Manipur/Factory/FORM 10.xlsx",
    "/Manipur/Factory/FORM 15 Muster.xlsx",
    "/Manipur/Factory/FORM 17 Audlt.xlsx",
    "/Manipur/Factory/FORM 19 Child.xlsx",
    "/Manipur/Factory/FORM 20 Leave.xlsx",
    "/Manipur/Factory/FORM 21 Leave book '.xlsx",
    "/Manipur/Factory/FORM 31.xlsx",
    "/Manipur/Factory/FORM 32.xlsx",
    "/Manipur/Factory/FORM 9.xlsx",
    "/Manipur/FORM 6 Register Of Employees ESIC.xls",
    "/Manipur/Minimum Wages/FORM I Register of Fines.xlsx",
    "/Manipur/Minimum Wages/FORM II Damges.xlsx",
    "/Manipur/Minimum Wages/FORM IV OverTime Register For Workers.xlsx",
    "/Manipur/Minimum Wages/FORM V Muster Roll.xlsx",
    "/Manipur/Minimum Wages/FORM X Register of Wages.xlsx",
    "/Manipur/Minimum Wages/FORM XI Wages Slip.xlsx",
    "/Manipur/S&E/Form I Wage.xlsx",
    "/Manipur/S&E/Form II Fine.xlsx",
    "/Manipur/S&E/Form IV.xlsx",
    "/Manipur/S&E/Form V.xlsx",
    "/Manipur/S&E/Form VI Leave.xlsx",
    "/Manipur/S&E/Form VII Register of OverTime.xlsx",
    "/Manipur/S&E/Form VIII.xlsx",
  ],
  "Meghalya": [
    "/Meghalya/CLRA/FORM XII Contractor.xlsx",
    "/Meghalya/CLRA/FORM XIII employemt.xlsx",
    "/Meghalya/CLRA/FORM XIX Wages.xlsx",
    "/Meghalya/CLRA/FORM XVI Muster.xlsx",
    "/Meghalya/CLRA/FORM XVII Muster.xlsx",
    "/Meghalya/CLRA/FORM XX Fine.xlsx",
    "/Meghalya/CLRA/FORM XXI Damgges.xlsx",
    "/Meghalya/CLRA/FORM XXII Advance.xlsx",
    "/Meghalya/CLRA/FORM XXIII Overtime.xlsx",
    "/Meghalya/Factory/FORM 10.xlsx",
    "/Meghalya/Factory/FORM 15.xlsx",
    "/Meghalya/Factory/FORM 17 Child.xlsx",
    "/Meghalya/Factory/FORM 19 adult.xlsx",
    "/Meghalya/Factory/FORM 20.xlsx",
    "/Meghalya/Factory/FORM 21.xlsx",
    "/Meghalya/Factory/FORM 36.xlsx",
    "/Meghalya/Factory/FORM 37.xlsx",
    "/Meghalya/Factory/FORM 7.xlsx",
    "/Meghalya/Factory/FORM 9.xlsx",
    "/Meghalya/FORM 6 Register Of Employees ESIC.xls",
    "/Meghalya/Form A Child labour.xlsx",
    "/Meghalya/FORM III Advance.xlsx",
    "/Meghalya/Minimum wages/FORM 6.xlsx",
    "/Meghalya/Minimum wages/FORM I Fine.xlsx",
    "/Meghalya/Minimum wages/FORM IV Overtime.xlsx",
    "/Meghalya/Minimum wages/FORM IV-A wages.xlsx",
    "/Meghalya/Minimum wages/FORM V Muster.xlsx",
    "/Meghalya/POW/FORM I.xlsx",
    "/Meghalya/POW/FORM II.xlsx",
    "/Meghalya/POW/FORM III.xlsx",
    "/Meghalya/POW/PoW Register of wages.xls",
    "/Meghalya/S&E/FORM I overtime.XLSX",
    "/Meghalya/S&E/FORM Q.XLSX",
    "/Meghalya/S&E/FORM R Reg overtimr.XLSX",
    "/Meghalya/S&E/FORM S Employmet.XLSX",
    "/Meghalya/S&E/FORM T Leave.XLSX",
  ],
  "Mizoram": [
    "/Mizoram/BOCW/FORM XIX Fine.XLSX",
    "/Mizoram/BOCW/FORM XV Person employee.xlsx",
    "/Mizoram/BOCW/FORM XVI Muster.XLSX",
    "/Mizoram/BOCW/FORM XVII Wages muster.XLSX",
    "/Mizoram/BOCW/FORM XVIII Muster.XLSX",
    "/Mizoram/BOCW/FORM XX Damges.XLSX",
    "/Mizoram/BOCW/FORM XXI advance.XLSX",
    "/Mizoram/BOCW/FORM XXII Overtime.XLSX",
    "/Mizoram/BOCW/FORM XXVI.xlsx",
    "/Mizoram/CLRA/FORM XII Contract.xlsx",
    "/Mizoram/CLRA/FORM XIII Person employed.xlsx",
    "/Mizoram/CLRA/FORM XIX wage.xlsx",
    "/Mizoram/CLRA/FORM XVI Muster Roll.xlsx",
    "/Mizoram/CLRA/FORM XVII Muster.xlsx",
    "/Mizoram/CLRA/FORM XX Fine.xlsx",
    "/Mizoram/CLRA/FORM XXI Damges.xlsx",
    "/Mizoram/CLRA/FORM XXII advance.xlsx",
    "/Mizoram/CLRA/FORM XXIII Overtime.xlsx",
    "/Mizoram/Factory/Form 11 Lift machines register.xlsx",
    "/Mizoram/Factory/Form 15 Overtime muster.xlsx",
    "/Mizoram/Factory/Form 22 Leave.xlsx",
    "/Mizoram/Factory/Form 23 Leave book.xlsx",
    "/Mizoram/Factory/FORM 24.xlsx",
    "/Mizoram/Factory/Form 34 Muster.xlsx",
    "/Mizoram/Factory/Form 35.xlsx",
    "/Mizoram/Factory/Form 36.xlsx",
    "/Mizoram/FORM 6 Register Of Employees ESIC.xls",
    "/Mizoram/FORM A Muster Woman worker.xlsx",
    "/Mizoram/Minimum wages/FORM I Fine.xlsx",
    "/Mizoram/Minimum wages/FORM II Damges.xlsx",
    "/Mizoram/Minimum wages/FORM IV Overtime.xlsx",
    "/Mizoram/Minimum wages/FORM V Muster.xlsx",
    "/Mizoram/Minimum wages/FORM XII Register of Wages.xlsx",
    "/Mizoram/Pow/FORM I Fine.xlsx",
    "/Mizoram/Pow/FORM II Damges.xlsx",
    "/Mizoram/Pow/FORM III Advance.xlsx",
    "/Mizoram/Pow/PoW Register of wages.xls",
    "/Mizoram/S&E/FORM EE.XLSX",
    "/Mizoram/S&E/FORM G.xlsx",
    "/Mizoram/S&E/FORM H Overtime.xlsx",
    "/Mizoram/S&E/FORM I Silp.xlsx",
    "/Mizoram/S&E/FORM J.xlsx",
    "/Mizoram/S&E/FORM K.xlsx",
    "/Mizoram/S&E/FORM O.xlsx",
    "/Mizoram/S&E/FORM P.xlsx",
    "/Mizoram/S&E/FORM Q.xlsx",
    "/Mizoram/S&E/FORM R.xlsx",
    "/Mizoram/S&E/FORM S.xlsx",
  ],
  "Nagaland": [
    "/Nagaland/CLRA/FORM XII Contractor.xlsx",
    "/Nagaland/CLRA/FORM XIII.xlsx",
    "/Nagaland/CLRA/FORM XIX slip.xlsx",
    "/Nagaland/CLRA/FORM XVI Muster Roll.xlsx",
    "/Nagaland/CLRA/FORM XVII ROW.xlsx",
    "/Nagaland/CLRA/FORM XX Fine.xlsx",
    "/Nagaland/CLRA/FORM XXI Register of Fines.xlsx",
    "/Nagaland/CLRA/FORM XXII ROA.xlsx",
    "/Nagaland/CLRA/FORM XXIII Register of OverTime.xlsx",
    "/Nagaland/FORM 6 Register Of Employees ESIC.xls",
    "/Nagaland/FORM A Child labour act.xlsx",
    "/Nagaland/Minimum wages/Form B Overtime.xlsx",
    "/Nagaland/Minimum wages/Form B wages register.xlsx",
    "/Nagaland/Minimum wages/Form C fine damges.xlsx",
    "/Nagaland/Minimum wages/Form D muster.xlsx",
    "/Nagaland/Minimum wages/FORM XI Wage Slip.xlsx",
    "/Nagaland/S&E/Form H.xlsx",
    "/Nagaland/S&E/Form I.xlsx",
    "/Nagaland/S&E/Form J.xlsx",
    "/Nagaland/S&E/Form N.xlsx",
    "/Nagaland/S&E/Form S.xlsx",
    "/Nagaland/S&E/Form T.xlsx",
  ],
  "Odisha": [
    "/Odisha/BOCW/Form XIX Fine.XLSX",
    "/Odisha/BOCW/Form XV Building worker.xlsx",
    "/Odisha/BOCW/Form XVI Muster.XLSX",
    "/Odisha/BOCW/Form XVII Muster.XLSX",
    "/Odisha/BOCW/Form XVIII Muster.XLSX",
    "/Odisha/BOCW/Form XX Damges.XLSX",
    "/Odisha/BOCW/Form XXI advance.XLSX",
    "/Odisha/BOCW/Form XXII overtime.XLSX",
    "/Odisha/BOCW/Form XXIII wage.XLSX",
    "/Odisha/BOCW/Form XXVI.xlsx",
    "/Odisha/CLRA/FORM 10 muster.docx",
    "/Odisha/CLRA/FORM 12 OVertime.docx",
    "/Odisha/CLRA/FORM IX worman employed.docx",
    "/Odisha/CLRA/FORM VIII Register Of Particulars Of Contractors.docx",
    "/Odisha/CLRA/FORM X Employment Card.docx",
    "/Odisha/CLRA/FORM XII Muster Roll.docx",
    "/Odisha/CLRA/FORM XIII Register Of Wages.docx",
    "/Odisha/CLRA/FORM XIX Register Of Overtime.docx",
    "/Odisha/CLRA/FORM XV Wage Slip.docx",
    "/Odisha/CLRA/FORM XVI Register Of Deduction For Damage Or Loss.xls",
    "/Odisha/CLRA/FORM XVII Register Of Fines.xls",
    "/Odisha/CLRA/FORM XVIII Register Of Advance.xls",
    "/Odisha/Factory/FORM No. 12.xlsx",
    "/Odisha/Factory/FORM NO. 15.xlsx",
    "/Odisha/Factory/FORM NO. 26 Accident.xlsx",
    "/Odisha/Factory/FORM NO. 31-A pre employment.xlsx",
    "/Odisha/Factory/FORM NO. 7-A.xlsx",
    "/Odisha/FORM 6 Register Of Employees ESIC.xls",
    "/Odisha/FORM D LWF.xlsx",
    "/Odisha/FORM E unclaimed wages.docx",
    "/Odisha/FORM F LWF.docx",
    "/Odisha/Industrial/FORM 10 muster.docx",
    "/Odisha/Minimum wages/FORM 10 (1) Muster.docx",
    "/Odisha/Minimum wages/FORM 10.docx",
    "/Odisha/Minimum wages/FORM 12.docx",
    "/Odisha/Minimum wages/FORM I.docx",
    "/Odisha/Minimum wages/FORM IV Overtime Register For Workers.docx",
    "/Odisha/Minimum wages/FORM V Muster Roll.docx",
    "/Odisha/Minimum wages/FORM X.docx",
    "/Odisha/Minimum wages/FORM XI Wage Slip.docx",
    "/Odisha/Minimum wages/FORM XII Working Hour Notice.docx",
    "/Odisha/PoW/FORM I fine.docx",
    "/Odisha/PoW/Register of wages_PoW - Odisha.xls",
    "/Odisha/S&E/FORM 10 muster.docx",
    "/Odisha/S&E/FORM 12 Overtime.docx",
    "/Odisha/S&E/FORM 8.docx",
  ],
  "Pan India": [
    "/Pan India/Bonus -Form D - Format.docx",
    "/Pan India/Bonus Register/Bonus form C 1.doc",
    "/Pan India/Bonus Register/Bonus return form D.doc",
    "/Pan India/Bonus Register/Form D.pdf",
    "/Pan India/Bonus Register/Form-C (Bonus).xls",
    "/Pan India/Half_Yearly_Return_FORM_XXIV_.xls",
    "/Pan India/Maternity Benefit_Return_2025.doc",
    "/Pan India/National & Fastival Holidays 2026.docx",
    "/Pan India/PAYMENT OF WAGES_FORM IV_2025.docx",
  ],
  "Panjab": [
    "/Panjab/BOCW/FORM I.xlsx",
    "/Panjab/BOCW/FORM VI.xlsx",
    "/Panjab/BOCW/FORM XIX.XLSX",
    "/Panjab/BOCW/FORM XVI.xlsx",
    "/Panjab/BOCW/FORM XVII.xlsx",
    "/Panjab/BOCW/FORM XVIII.xlsx",
    "/Panjab/BOCW/FORM XX.xlsx",
    "/Panjab/BOCW/FORM XXI.xlsx",
    "/Panjab/BOCW/FORM XXII.xlsx",
    "/Panjab/BOCW/FORM XXIII.xlsx",
    "/Panjab/BOCW/FORM XXIV.xlsx",
    "/Panjab/CLRA/FORM XII Register Of Contractors.docx",
    "/Panjab/CLRA/FORM XIX Wage Slip.docx",
    "/Panjab/CLRA/FORM XVII Register Of Wages.docx",
    "/Panjab/CLRA/FORM XX Register Of Deductions For Damage Or Loss.docx",
    "/Panjab/CLRA/FORM XXI Register Of Fines.docx",
    "/Panjab/CLRA/FORM XXII Register Of Advances.docx",
    "/Panjab/CLRA/FORM XXIII Register Of Overtime.docx",
    "/Panjab/CLRA/FORMXIII Register Of Workmen Employed.docx",
    "/Panjab/CLRA/FORMXVI Muster Roll.docx",
    "/Panjab/Factory/FORM 10 Overtime Muster Roll for Exempted Workers.xlsx",
    "/Panjab/Factory/Form 12 Register of Adult Workers.xlsx",
    "/Panjab/Factory/Form 14 Register of Child Workers.xlsx",
    "/Panjab/Factory/Form 15 Register of Leave with Wages.xlsx",
    "/Panjab/Factory/Form 23 Record of the Examination of Hoist and Lift.xlsx",
    "/Panjab/Factory/Form 25 Muster Roll.xlsx",
    "/Panjab/Factory/FORM 7A Register Of Workers.xlsx",
    "/Panjab/FORM 6 Register Of Employees ESIC.xls",
    "/Panjab/FORM A Child act.docx",
    "/Panjab/FORM A Muster Roll woman.docx",
    "/Panjab/MInimum/Form A.xls",
    "/Panjab/MInimum/FORM I Register Of Fines (1).docx",
    "/Panjab/MInimum/FORM I Register Of Fines (2).docx",
    "/Panjab/MInimum/FORM I Register Of Fines.docx",
    "/Panjab/MInimum/FORM II (1).docx",
    "/Panjab/MInimum/FORM II.docx",
    "/Panjab/MInimum/FORM IV Overtime Register For Workers.docx",
    "/Panjab/MInimum/FORM XI Wage Slips.docx",
    "/Panjab/MInimum/Muster Roll in Form V MW_Punjab.xls",
    "/Panjab/MInimum/Register of wages-Form X_ Punjab.xls",
    "/Panjab/PoW/FORM VI Fine.xlsx",
    "/Panjab/S&E/FORM B Register Of Fines Realised And Unpaid.docx",
    "/Panjab/S&E/FORM C Register Of Employees.docx",
    "/Panjab/S&E/FORM D Register Of Wages.docx",
    "/Panjab/S&E/FORM E Register Of Deductions.docx",
  ],
  "Puducherry": [
    "/Puducherry/BOCW/FORM XIX Fine.xlsx",
    "/Puducherry/BOCW/FORM XV.xlsx",
    "/Puducherry/BOCW/FORM XX Damges.xlsx",
    "/Puducherry/BOCW/FORM XXI Advance.xlsx",
    "/Puducherry/BOCW/FORM XXII Regsiter OVertime.xlsx",
    "/Puducherry/BOCW/FORM XXIII Wage.xlsx",
    "/Puducherry/BOCW/FORM XXVI.xlsx",
    "/Puducherry/CLRA/Form - II (1) Contractor.xlsx",
    "/Puducherry/CLRA/Form - II.xlsx",
    "/Puducherry/CLRA/Form -III (1).xlsx",
    "/Puducherry/CLRA/Form -III (2).xlsx",
    "/Puducherry/CLRA/Form -III.xlsx",
    "/Puducherry/CLRA/FORM XIX wage.xlsx",
    "/Puducherry/Facotry/FORM 11 Child.xlsx",
    "/Puducherry/Facotry/FORM 12 Audlt.xlsx",
    "/Puducherry/Facotry/FORM 13 Audlt.xlsx",
    "/Puducherry/Facotry/FORM 14 Child.xlsx",
    "/Puducherry/Facotry/FORM 16A.xlsx",
    "/Puducherry/Facotry/FORM 23.xlsx",
    "/Puducherry/Facotry/FORM 24.xlsx",
    "/Puducherry/Facotry/FORM 25.xlsx",
    "/Puducherry/Facotry/FORM 26.xlsx",
    "/Puducherry/Facotry/FORM 7A.xlsx",
    "/Puducherry/FORM 6 Register Of Employees ESIC.xls",
    "/Puducherry/Minimumwages/Form -III (1) Fine.xlsx",
    "/Puducherry/Minimumwages/Form -III (1) Overtime.xlsx",
    "/Puducherry/Minimumwages/Form -III (1) wages.xlsx",
    "/Puducherry/Minimumwages/Form -III.xlsx",
    "/Puducherry/PoW/Form -III.xlsx",
    "/Puducherry/S&E/Form - II.xlsx",
    "/Puducherry/S&E/Form -III (1) advance.xlsx",
    "/Puducherry/S&E/Form -III (1)w.xlsx",
    "/Puducherry/S&E/Form VII.xlsx",
    "/Puducherry/S&E/Form XI (1).xlsx",
    "/Puducherry/S&E/Form XI.xlsx",
  ],
  "RAJASTHAN": [
    "/RAJASTHAN/BOCW/FORM XI.xlsx",
    "/RAJASTHAN/BOCW/FORM XII.XLSX",
    "/RAJASTHAN/BOCW/FORM XIII Muster.XLSX",
    "/RAJASTHAN/BOCW/FORM XIV Muster.XLSX",
    "/RAJASTHAN/BOCW/FORM XIX.XLSX",
    "/RAJASTHAN/BOCW/FORM XV.XLSX",
    "/RAJASTHAN/BOCW/FORM XVI.XLSX",
    "/RAJASTHAN/BOCW/FORM XVII.XLSX",
    "/RAJASTHAN/BOCW/FORM XVIII.XLSX",
    "/RAJASTHAN/BOCW/FORM XXIII.xlsx",
    "/RAJASTHAN/CLRA/FORM IX Workman.docx",
    "/RAJASTHAN/CLRA/FORM VIII.docx",
    "/RAJASTHAN/CLRA/FORM XII Muster.docx",
    "/RAJASTHAN/CLRA/FORM XIII Muster.docx",
    "/RAJASTHAN/CLRA/FORM XIX Overtime.docx",
    "/RAJASTHAN/CLRA/FORM XV wage.docx",
    "/RAJASTHAN/CLRA/FORM XVI Advance.docx",
    "/RAJASTHAN/CLRA/FORM XVII Damges.docx",
    "/RAJASTHAN/CLRA/FORM XVIII Fine.docx",
    "/RAJASTHAN/Factory/FORM NO. 11 Muster adult.xlsx",
    "/RAJASTHAN/Factory/FORM NO. 11 Muster overtime.xlsx",
    "/RAJASTHAN/Factory/FORM NO. 13 adult.xlsx",
    "/RAJASTHAN/Factory/FORM NO. 16 Leave.xlsx",
    "/RAJASTHAN/Factory/FORM NO. 17.xlsx",
    "/RAJASTHAN/Factory/FORM NO. 19.xlsx",
    "/RAJASTHAN/Factory/FORM NO. 30.xlsx",
    "/RAJASTHAN/Factory/FORM NO. 34.xlsx",
    "/RAJASTHAN/Factory/FORM NO. 7.xlsx",
    "/RAJASTHAN/Factory/FORM NO. 8.xlsx",
    "/RAJASTHAN/FORM 2 Child labour act.pdf",
    "/RAJASTHAN/FORM 6 Register Of Employees ESIC.xls",
    "/RAJASTHAN/FORM A woman worker.docx",
    "/RAJASTHAN/GATUITY/FORM I.docx",
    "/RAJASTHAN/GATUITY/FORM J.docx",
    "/RAJASTHAN/GATUITY/FORM K.docx",
    "/RAJASTHAN/GATUITY/FORM L.docx",
    "/RAJASTHAN/IMWA/Form XII.xlsx",
    "/RAJASTHAN/IMWA/Form XIII.xlsx",
    "/RAJASTHAN/IMWA/Form XIX FINE DAMGES ADVANCE.xlsx",
    "/RAJASTHAN/IMWA/Form XV Allowance.xlsx",
    "/RAJASTHAN/IMWA/Form XVI Allowance.xlsx",
    "/RAJASTHAN/IMWA/Form XVII Muster.xlsx",
    "/RAJASTHAN/IMWA/Form XVIII Muster.xlsx",
    "/RAJASTHAN/IMWA/Form XXII Overtimr.xlsx",
    "/RAJASTHAN/Minimum wges/FORM I Fine.docx",
    "/RAJASTHAN/Minimum wges/FORM II Damges.docx",
    "/RAJASTHAN/Minimum wges/FORM IV Overtime.docx",
    "/RAJASTHAN/Minimum wges/FORM V muster.docx",
    "/RAJASTHAN/Minimum wges/FORM XI Wages.docx",
    "/RAJASTHAN/Minimum wges/FORM XII Slip.docx",
    "/RAJASTHAN/PoW/FORM I.docx",
    "/RAJASTHAN/PoW/FORM II.docx",
    "/RAJASTHAN/PoW/FORM III.docx",
    "/RAJASTHAN/PoW/FORM VII.docx",
    "/RAJASTHAN/PoW/PoW Register of wages.xls",
    "/RAJASTHAN/S&E/FORM 11 register.xlsx",
    "/RAJASTHAN/S&E/FORM 12.xlsx",
    "/RAJASTHAN/S&E/FORM 13.docx",
    "/RAJASTHAN/S&E/FORM 14.docx",
    "/RAJASTHAN/S&E/FORM 15.docx",
    "/RAJASTHAN/S&E/FORM 7 holidays.docx",
    "/RAJASTHAN/S&E/FORM 8 Leave.docx",
  ],
  "Sikkim": [
    "/Sikkim/CLRA/Form XII Contractor.xlsx",
    "/Sikkim/CLRA/Form XIII Workmen.xlsx",
    "/Sikkim/CLRA/Form XIX.xlsx",
    "/Sikkim/CLRA/Form XVI Muster Roll.xlsx",
    "/Sikkim/CLRA/Form XVII Register Of Wages.xlsx",
    "/Sikkim/CLRA/Form XX Fine.xlsx",
    "/Sikkim/CLRA/Form XXI Register of Fines.xlsx",
    "/Sikkim/CLRA/Form XXII Register Of Advances.xlsx",
    "/Sikkim/CLRA/Form XXIII Register of OverTime.xlsx",
    "/Sikkim/FORM 6 Register Of Employees ESIC.xls",
    "/Sikkim/FORM A Maternity benefit.xlsx",
    "/Sikkim/Minimum wages/Form I Fine.xlsx",
    "/Sikkim/Minimum wages/Form II Damges.xlsx",
    "/Sikkim/Minimum wages/Form III annual.xlsx",
    "/Sikkim/Minimum wages/Form IV OT Register_MW - Sikkim.xlsx",
    "/Sikkim/Minimum wages/Form V muster.xlsx",
    "/Sikkim/Minimum wages/Form XIV emp register.xlsx",
    "/Sikkim/Minimum wages/Form XV.xlsx",
    "/Sikkim/Minimum wages/MW Register of wages.xls",
    "/Sikkim/PoW/Form I Fine.xlsx",
    "/Sikkim/PoW/Form II Damges.xlsx",
    "/Sikkim/PoW/Form III Advances.xlsx",
    "/Sikkim/PoW/Form IV annual ret.xlsx",
    "/Sikkim/PoW/POW-Register of wages.xls",
    "/Sikkim/S&E/Form I.xlsx",
    "/Sikkim/S&E/Form J.xlsx",
    "/Sikkim/S&E/Form K.xlsx",
    "/Sikkim/S&E/Form L.xlsx",
    "/Sikkim/S&E/Form N leave.xlsx",
    "/Sikkim/S&E/Form O Leave book.xlsx",
    "/Sikkim/S&E/Form XV wages slip.xlsx",
  ],
  "Tamil Nadu": [
    "/Tamil Nadu/Abstract Of Child And Adolescent Labour Prohibition And Regulation Act 1986.pdf",
    "/Tamil Nadu/BOCW/Form XIX Fine.xlsx",
    "/Tamil Nadu/BOCW/Form XV Person emplyed.xlsx",
    "/Tamil Nadu/BOCW/Form XVI Muster.xlsx",
    "/Tamil Nadu/BOCW/Form XVII Muster.xlsx",
    "/Tamil Nadu/BOCW/Form XVIII Muster.xlsx",
    "/Tamil Nadu/BOCW/Form XX Damges.xlsx",
    "/Tamil Nadu/BOCW/Form XXI Advance.xlsx",
    "/Tamil Nadu/BOCW/Form XXII OVertime.xlsx",
    "/Tamil Nadu/BOCW/Form XXIII Wage book.xlsx",
    "/Tamil Nadu/BOCW/Form XXVI Register.xlsx",
    "/Tamil Nadu/CLRA/FORM No. XXIX Register Of Advances, Deductions For Damages Or Loss And Fines.docx",
    "/Tamil Nadu/CLRA/FORM No. XXVI Register Of Employment.docx",
    "/Tamil Nadu/CLRA/FORM No. XXVII Register Of Wages.docx",
    "/Tamil Nadu/CLRA/FORM No. XXVIII Wage Slip.docx",
    "/Tamil Nadu/CLRA/FORM XII Register of Contractor.docx",
    "/Tamil Nadu/Factory/FORM NO. 10.docx",
    "/Tamil Nadu/Factory/Form No. 12 Audlt.docx",
    "/Tamil Nadu/Factory/FORM NO. 12.xlsx",
    "/Tamil Nadu/Factory/FORM NO. 15 Leave.xlsx",
    "/Tamil Nadu/Factory/FORM NO. 17 Heath checkup.docx",
    "/Tamil Nadu/Factory/FORM NO. 22 Annual Retun.docx",
    "/Tamil Nadu/Factory/Form No. 25-A Adult.docx",
    "/Tamil Nadu/Factory/FORM NO. 25-C ID.docx",
    "/Tamil Nadu/Factory/FORM NO. 25.xlsx",
    "/Tamil Nadu/Factory/FORM NO. 27 pre employment.docx",
    "/Tamil Nadu/Factory/FORM NO. 28.docx",
    "/Tamil Nadu/Factory/FORM NO. 29.docx",
    "/Tamil Nadu/Factory/FORM NO. 35.docx",
    "/Tamil Nadu/Factory/FORM NO. 36.docx",
    "/Tamil Nadu/Factory/FORM NO. 39 Health Register.docx",
    "/Tamil Nadu/Factory/FORM NO. 7.docx",
    "/Tamil Nadu/FORM 2 Child labour act.docx",
    "/Tamil Nadu/FORM 6 Register Of Employees ESIC.xls",
    "/Tamil Nadu/IMWA/FORM XII Register Contractor.xlsx",
    "/Tamil Nadu/IMWA/FORM XIII Register person employed.xlsx",
    "/Tamil Nadu/IMWA/FORM XIX Damges.xlsx",
    "/Tamil Nadu/IMWA/FORM XV Allowances.xlsx",
    "/Tamil Nadu/IMWA/FORM XVI allowance.xlsx",
    "/Tamil Nadu/IMWA/FORM XVII Muster.xlsx",
    "/Tamil Nadu/IMWA/FORM XVIII wages.xlsx",
    "/Tamil Nadu/IMWA/FORM XX Fine.xlsx",
    "/Tamil Nadu/IMWA/FORM XXI Advance.xlsx",
    "/Tamil Nadu/IMWA/FORM XXII Overtime.xlsx",
    "/Tamil Nadu/LWF/FORM A.docx",
    "/Tamil Nadu/LWF/FORM B Register Of Wages.docx",
    "/Tamil Nadu/LWF/FORM C Register Of Fines And Unpaid Accumulations 1.docx",
    "/Tamil Nadu/LWF/FORM C Register Of Fines And Unpaid Accumulations.docx",
    "/Tamil Nadu/Minimum wages/FORM I Register Of Fines.docx",
    "/Tamil Nadu/Minimum wages/FORM II Register Of Deductions For Damage Or Loss.docx",
    "/Tamil Nadu/Minimum wages/FORM III Annual Returns.docx",
    "/Tamil Nadu/Minimum wages/FORM IV Overtime Register For Workers.docx",
    "/Tamil Nadu/Minimum wages/FORM V Muster.docx",
    "/Tamil Nadu/Minimum wages/FORM XI Register of Employees.docx",
    "/Tamil Nadu/Minimum wages/MW Register of wages.xls",
    "/Tamil Nadu/Minimum wages/Wage Slip under the Minimum Wages (Tamil Nadu) Rules, 1953.docx",
    "/Tamil Nadu/POW/Display of Notice under of Payment of wages act.docx",
    "/Tamil Nadu/POW/FORM I Fine.docx",
    "/Tamil Nadu/POW/FORM I Nomination and Declaration Form.docx",
    "/Tamil Nadu/POW/FORM II Damges.docx",
    "/Tamil Nadu/POW/FORM III Advance.docx",
    "/Tamil Nadu/POW/FORM IV Annual ret.docx",
    "/Tamil Nadu/POW/FORM V Abstract Of Payment Of Wages Act And Rules (Tamil Version).pdf",
    "/Tamil Nadu/POW/FORM V Abstract Of Payment Of Wages Act And Rules.pdf",
    "/Tamil Nadu/POW/FORM VI Wages Rate.docx",
    "/Tamil Nadu/POW/FORM VIII.docx",
    "/Tamil Nadu/POW/Wage Slip under the Tamil Nadu Payment Of Wages Rules, 1937.docx",
    "/Tamil Nadu/S&E/FORM R.docx",
    "/Tamil Nadu/S&E/FORM T Wage silp.docx",
    "/Tamil Nadu/S&E/FORM U.xlsx",
    "/Tamil Nadu/S&E/FORM V.xlsx",
    "/Tamil Nadu/S&E/FORM W maintance register.xlsx",
    "/Tamil Nadu/S&E/FORM W.xlsx",
    "/Tamil Nadu/S&E/FORM X.xlsx",
    "/Tamil Nadu/Tamil nadu industrial act/FORM 1 Woman worker.xlsx",
    "/Tamil Nadu/Tamil nadu industrial act/FORM A Muster Roll woman worker.docx",
    "/Tamil Nadu/Tamil nadu industrial act/FORM No. VI.docx",
  ],
  "Telangana": [
    "/Telangana/BOCW/Annual Return FORM- I.xlsx",
    "/Telangana/BOCW/FORM XV Register of person employed.xlsx",
    "/Telangana/BOCW/FORM XXIII wage book.XLSX",
    "/Telangana/BOCW/FORM XXVI Register of periodical.xlsx",
    "/Telangana/BOCW/Furnishing Of Return And Integrated Register By An Establishment Under Various Labour Laws (1).pdf",
    "/Telangana/BOCW/Furnishing Of Return And Integrated Register By An Establishment Under Various Labour Laws (2).pdf",
    "/Telangana/BOCW/Furnishing Of Return And Integrated Register By An Establishment Under Various Labour Laws.pdf",
    "/Telangana/BOCW/Integrated Register FORM II Fine Damges.xlsx",
    "/Telangana/BOCW/Integrated Register FORM II Muster.xlsx",
    "/Telangana/BOCW/Integrated Register FORM II Overtime.xlsx",
    "/Telangana/BOCW/Integrated Register FORM III advances.xlsx",
    "/Telangana/BOCW/Integrated Register FORM III OVertime.xlsx",
    "/Telangana/BOCW/Integrated Register FORM III Register of wages.xlsx",
    "/Telangana/CLRA/FORM XII Register of contractor.docx",
    "/Telangana/CLRA/FORM XIII Workman.docx",
    "/Telangana/CLRA/FORM XIV Wages card.docx",
    "/Telangana/CLRA/FORM XVI Muster.docx",
    "/Telangana/CLRA/Furnishing Of Return And Integrated Register By An Establishment Under Various Labour Laws (1).pdf",
    "/Telangana/CLRA/Furnishing Of Return And Integrated Register By An Establishment Under Various Labour Laws (2).pdf",
    "/Telangana/CLRA/Furnishing Of Return And Integrated Register By An Establishment Under Various Labour Laws.pdf",
    "/Telangana/CLRA/Integrated Register FORM II Fine.xlsx",
    "/Telangana/CLRA/Integrated Register FORM II Overtime.xlsx",
    "/Telangana/CLRA/Integrated Register FORM II Wages.xlsx",
    "/Telangana/CLRA/Integrated Register FORM III Fine.xlsx",
    "/Telangana/CLRA/Integrated Register FORM III Overtimr.xlsx",
    "/Telangana/CLRA/Integrated Register FORM III Wages.xlsx",
    "/Telangana/Factory/Annual Return FORM- I.xlsx",
    "/Telangana/Factory/FORM 25 Leave Register.xlsx",
    "/Telangana/Factory/FORM NO. 27 C Pre Emplmt.xlsx",
    "/Telangana/Factory/FORM NO. 35.xlsx",
    "/Telangana/Factory/FORM NO. 38.xlsx",
    "/Telangana/Factory/Furnishing Of Return And Integrated Register By An Establishment Under Various Labour Laws (1).pdf",
    "/Telangana/Factory/Furnishing Of Return And Integrated Register By An Establishment Under Various Labour Laws.pdf",
    "/Telangana/Factory/Integrated Register FORM II Audlt.xlsx",
    "/Telangana/Factory/Integrated Register FORM III Audlt.xlsx",
    "/Telangana/FORM 6 Register Of Employees ESIC.xls",
    "/Telangana/FORM A Child Labour act.docx",
    "/Telangana/Gratuity/FORM I Application For Gratuity By An Employee.docx",
    "/Telangana/Gratuity/FORM J Application For Gratuity By A Nominee.docx",
    "/Telangana/Gratuity/FORM K Application For Gratuity By A Legal Heir.docx",
    "/Telangana/Gratuity/FORM L Notice For Payment Of Gratuity.docx",
    "/Telangana/IMWA/FORM XIV Register Contractor.xlsx",
    "/Telangana/IMWA/FORM XIX Muster.xlsx",
    "/Telangana/IMWA/FORM XV Register of Person employed.xlsx",
    "/Telangana/IMWA/FORM XVII Allowance '.xlsx",
    "/Telangana/IMWA/FORM XVIII Allowances.xlsx",
    "/Telangana/IMWA/FORM XX Wages.xlsx",
    "/Telangana/IMWA/FORM XXIII Advance.xlsx",
    "/Telangana/IMWA/FORM XXIV Damges.xlsx",
    "/Telangana/IMWA/FORM XXV Overtime.xlsx",
    "/Telangana/IMWA/FORM XXVIII Annual Return.xlsx",
    "/Telangana/LWF/FORM D WAges Register.docx",
    "/Telangana/LWF/FORM E.docx",
    "/Telangana/LWF/FORM F Retrun.xlsx",
    "/Telangana/LWF/FORM G.docx",
    "/Telangana/Minimum wages/Annual Return FORM- I.xlsx",
    "/Telangana/Minimum wages/Furnishing Of Return And Integrated Register By An Establishment Under Various Labour Laws (1).pdf",
    "/Telangana/Minimum wages/Furnishing Of Return And Integrated Register By An Establishment Under Various Labour Laws (2).pdf",
    "/Telangana/Minimum wages/Furnishing Of Return And Integrated Register By An Establishment Under Various Labour Laws.pdf",
    "/Telangana/Minimum wages/Integrated Register FORM II Fine.xlsx",
    "/Telangana/Minimum wages/Integrated Register FORM II.xlsx",
    "/Telangana/Minimum wages/Integrated Register FORM III Damges.xlsx",
    "/Telangana/Minimum wages/Integrated Register FORM III.xlsx",
    "/Telangana/POW/Annual Return FORM- I.xlsx",
    "/Telangana/POW/FORM V PT.xlsx",
    "/Telangana/POW/Furnishing Of Return And Integrated Register By An Establishment Under Various Labour Laws (1).pdf",
    "/Telangana/POW/Furnishing Of Return And Integrated Register By An Establishment Under Various Labour Laws.pdf",
    "/Telangana/POW/Integrated Register FORM II.xlsx",
    "/Telangana/POW/Integrated Register FORM III.xlsx",
    "/Telangana/S&E/FORM XXII Employemt.docx",
    "/Telangana/S&E/FORM XXV Leave.docx",
    "/Telangana/S&E/Furnishing Of Return And Integrated Register By An Establishment Under Various Labour Laws (1).pdf",
    "/Telangana/S&E/Furnishing Of Return And Integrated Register By An Establishment Under Various Labour Laws (2).pdf",
    "/Telangana/S&E/Furnishing Of Return And Integrated Register By An Establishment Under Various Labour Laws.pdf",
    "/Telangana/S&E/Integrated Register FORM II Advacne.xlsx",
    "/Telangana/S&E/Integrated Register FORM II Damges.xlsx",
    "/Telangana/S&E/Integrated Register FORM II wages.xlsx",
    "/Telangana/S&E/Integrated Register FORM III Advance.xlsx",
    "/Telangana/S&E/Integrated Register FORM III Damges.xlsx",
    "/Telangana/S&E/Integrated Register FORM III wages.xlsx",
  ],
  "Tripura": [
    "/Tripura/CLRA/FORM XII Register of contractor.xlsx",
    "/Tripura/CLRA/FORM XIII Workmen.xlsx",
    "/Tripura/CLRA/FORM XIX.xlsx",
    "/Tripura/CLRA/FORM XVI Muster Roll.xlsx",
    "/Tripura/CLRA/FORM XVII Rate Of Wages.xlsx",
    "/Tripura/CLRA/FORM XX Damges.xlsx",
    "/Tripura/CLRA/FORM XXI Register of Fines.xlsx",
    "/Tripura/CLRA/FORM XXII Register Of Advances.xlsx",
    "/Tripura/CLRA/FORM XXIII Register of OverTime.xlsx",
    "/Tripura/CLRA/FORM XXV Annual ret.xlsx",
    "/Tripura/Factory/FORM 12.xlsx",
    "/Tripura/Factory/FORM 13.xlsx",
    "/Tripura/Factory/FORM 20 OT Muster Roll.xlsx",
    "/Tripura/Factory/FORM 22 Register of Adult & Child.xlsx",
    "/Tripura/Factory/FORM 24 Register of Adult & child.xlsx",
    "/Tripura/Factory/FORM 25 Leave.xlsx",
    "/Tripura/Factory/FORM 26 leave.xlsx",
    "/Tripura/Factory/FORM 35 Annual ret.xlsx",
    "/Tripura/FORM 6 Register Of Employees ESIC.xls",
    "/Tripura/Gratuity/FORM I Application for Gratuity.xlsx",
    "/Tripura/Gratuity/FORM J.xlsx",
    "/Tripura/Gratuity/FORM K.xlsx",
    "/Tripura/Gratuity/FORM L.xlsx",
    "/Tripura/Minimum wages/FORM B Overtime.xlsx",
    "/Tripura/Minimum wages/FORM B Register of wages.xlsx",
    "/Tripura/Minimum wages/FORM C Fine.xlsx",
    "/Tripura/Minimum wages/FORM D Muster.xlsx",
    "/Tripura/Minimum wages/FORM I Register of Hours work.xlsx",
    "/Tripura/Minimum wages/FORM J Leave.xlsx",
    "/Tripura/Minimum wages/FORM R.xlsx",
    "/Tripura/Minimum wages/FORM S.xlsx",
    "/Tripura/Minimum wages/Form U Register of emplemt.xlsx",
    "/Tripura/POW/FORM I Fine.xlsx",
    "/Tripura/POW/FORM II Damges.xlsx",
    "/Tripura/POW/FORM III Advance.xlsx",
    "/Tripura/POW/FORM IV annual ret.xlsx",
    "/Tripura/POW/Form VI PoW Register of wages.xls",
    "/Tripura/S&E/FORM K wage register.xlsx",
  ],
  "Uttar Pradesh": [
    "/Uttar Pradesh/BOCW/Form 13 wage book.xlsx",
    "/Uttar Pradesh/BOCW/Form 28 Register Beneficires.xlsx",
    "/Uttar Pradesh/CLRA/FORM XII Register of Contractor.xlsx",
    "/Uttar Pradesh/CLRA/FORM XII.docx",
    "/Uttar Pradesh/CLRA/FORM XIII Workmen.xlsx",
    "/Uttar Pradesh/CLRA/FORM XIX wage s.docx",
    "/Uttar Pradesh/CLRA/FORM XIX Wage silp.xlsx",
    "/Uttar Pradesh/CLRA/FORM XVI Muster.xlsx",
    "/Uttar Pradesh/CLRA/FORM XVII register of wages.xlsx",
    "/Uttar Pradesh/CLRA/FORM XX Fine.docx",
    "/Uttar Pradesh/CLRA/FORM XX Fine.xlsx",
    "/Uttar Pradesh/CLRA/FORM XXI Damges.xlsx",
    "/Uttar Pradesh/CLRA/FORM XXII Advnces.xlsx",
    "/Uttar Pradesh/CLRA/FORM XXIII OT.docx",
    "/Uttar Pradesh/CLRA/FORM XXIII OT.xlsx",
    "/Uttar Pradesh/CLRA/FORM XXV Annual ret.xlsx",
    "/Uttar Pradesh/Factory/FORM 10 OT.xlsx",
    "/Uttar Pradesh/Factory/FORM 12 Adult & child.xlsx",
    "/Uttar Pradesh/Factory/FORM 14 Leave.xlsx",
    "/Uttar Pradesh/Factory/FORM 15 Leave.xlsx",
    "/Uttar Pradesh/Factory/FORM 21 Annual Ret.xlsx",
    "/Uttar Pradesh/Factory/FORM 25 Authories workmen registrer.xlsx",
    "/Uttar Pradesh/Factory/FORM 27 Pre empl.xlsx",
    "/Uttar Pradesh/FORM 6 Register Of Employees ESIC.xls",
    "/Uttar Pradesh/FORM A Child Labour Act.docx",
    "/Uttar Pradesh/Gratuity/FORM I.docx",
    "/Uttar Pradesh/Gratuity/FORM J.docx",
    "/Uttar Pradesh/Gratuity/FORM K.docx",
    "/Uttar Pradesh/Gratuity/FORM L.docx",
    "/Uttar Pradesh/Minimum wages/FORM I Fine.docx",
    "/Uttar Pradesh/Minimum wages/FORM II.docx",
    "/Uttar Pradesh/Minimum wages/FORM III Annual ret.docx",
    "/Uttar Pradesh/Minimum wages/FORM IV muster.docx",
    "/Uttar Pradesh/Minimum wages/FORM XVII OT.docx",
    "/Uttar Pradesh/Minimum wages/MW-Register of wages.xls",
    "/Uttar Pradesh/Minimum wages/Wage Slip under the Uttar Pradesh Minimum Wages Rules, 1952.docx",
    "/Uttar Pradesh/POW/FORM I Fine.docx",
    "/Uttar Pradesh/POW/FORM II Damges.docx",
    "/Uttar Pradesh/POW/FORM III Advances.docx",
    "/Uttar Pradesh/POW/FORM IV Annual ret.docx",
    "/Uttar Pradesh/UP Dokkan/FORM CC Register of attendance.docx",
    "/Uttar Pradesh/UP Dokkan/FORM D.docx",
    "/Uttar Pradesh/UP Dokkan/FORM E Fine.docx",
    "/Uttar Pradesh/UP Dokkan/FORM G wages register.docx",
    "/Uttar Pradesh/UP Dokkan/FORM H.docx",
  ],
  "Uttarakhand": [
    "/Uttarakhand/Abstract Of Child And Adolescent Labour (Prohibition And Regulation) Act, 1986.pdf",
    "/Uttarakhand/BOCW/Form XIV Reports of accident.xlsx",
    "/Uttarakhand/BOCW/Form XIX Fine.XLSX",
    "/Uttarakhand/BOCW/Form XV Register of Person emploed.xlsx",
    "/Uttarakhand/BOCW/Form XVI Muster Roll.XLSX",
    "/Uttarakhand/BOCW/Form XVII Muster.XLSX",
    "/Uttarakhand/BOCW/Form XVIII Muster roll.XLSX",
    "/Uttarakhand/BOCW/Form XX Damges.XLSX",
    "/Uttarakhand/BOCW/Form XXI Advances.XLSX",
    "/Uttarakhand/BOCW/Form XXII Register of OT.XLSX",
    "/Uttarakhand/BOCW/FORM XXIII-Wage Book -Uttaranchal BOCW Rules, 2005.docx",
    "/Uttarakhand/BOCW/Form XXVI register of Periodical.xlsx",
    "/Uttarakhand/BOCW/Form XXXII ID.xlsx",
    "/Uttarakhand/CLRA/FORM XII Contractor.docx",
    "/Uttarakhand/CLRA/FORM XIII Workmen empl.docx",
    "/Uttarakhand/CLRA/FORM XIV Employment card.docx",
    "/Uttarakhand/CLRA/FORM XIX wage slip.docx",
    "/Uttarakhand/CLRA/FORM XVI Muster.docx",
    "/Uttarakhand/CLRA/FORM XVII Wages register.docx",
    "/Uttarakhand/CLRA/FORM XX Fine.docx",
    "/Uttarakhand/CLRA/FORM XXI Damges.docx",
    "/Uttarakhand/CLRA/FORM XXII Advance.docx",
    "/Uttarakhand/CLRA/FORM XXIII OT.docx",
    "/Uttarakhand/CLRA/FORM XXV Annual return.docx",
    "/Uttarakhand/Factory/FORM No. 14 Register Leave.xlsx",
    "/Uttarakhand/Factory/FORM No. 15 Leave book.xlsx",
    "/Uttarakhand/Factory/FORM No. 16 Leave form.xlsx",
    "/Uttarakhand/Factory/FORM No. 21 Annual Return.xlsx",
    "/Uttarakhand/Factory/FORM No. 25 Register of  Authorised worker & Tight fiiting.xlsx",
    "/Uttarakhand/Factory/FORM No. 27 Pre Employment.xlsx",
    "/Uttarakhand/Factory/FORM No.10 OT for Exempted workers.xlsx",
    "/Uttarakhand/Factory/FORM No.12 Adult.xlsx",
    "/Uttarakhand/Factory/FORM No.13 Child.xlsx",
    "/Uttarakhand/FORM 6 Register Of Employees ESIC.xls",
    "/Uttarakhand/FORM A Child Labour act.docx",
    "/Uttarakhand/Gratuity/FORM I.docx",
    "/Uttarakhand/Gratuity/FORM J.docx",
    "/Uttarakhand/Gratuity/FORM K.docx",
    "/Uttarakhand/Gratuity/FORM L.docx",
    "/Uttarakhand/Minimum wages/Abstract Of The Minimum Wages Act, 1948 (Hindi Version).pdf",
    "/Uttarakhand/Minimum wages/FORM I Fine.docx",
    "/Uttarakhand/Minimum wages/FORM II Damges.docx",
    "/Uttarakhand/Minimum wages/FORM III Annual Return.docx",
    "/Uttarakhand/Minimum wages/Form IV Muster Roll.xls",
    "/Uttarakhand/Minimum wages/FORM XI Abstract.docx",
    "/Uttarakhand/Minimum wages/FORM XII Absract Under The Minimum Wages Act, 1948.pdf",
    "/Uttarakhand/Minimum wages/FORM XIII Rate of minimum wages.docx",
    "/Uttarakhand/Minimum wages/FORM XVII OT.docx",
    "/Uttarakhand/Minimum wages/MW- Register of wages.xls",
    "/Uttarakhand/POW/FORM I Fine.docx",
    "/Uttarakhand/POW/FORM II Damges.docx",
    "/Uttarakhand/POW/FORM III Advance.docx",
    "/Uttarakhand/Utt Dookan Adhiniyam/Register to be maintained/FORM A.docx",
    "/Uttarakhand/Utt Dookan Adhiniyam/Register to be maintained/FORM B.docx",
    "/Uttarakhand/Utt Dookan Adhiniyam/Register to be maintained/FORM CC.docx",
    "/Uttarakhand/Utt Dookan Adhiniyam/Register to be maintained/FORM D.docx",
    "/Uttarakhand/Utt Dookan Adhiniyam/Register to be maintained/FORM E.docx",
    "/Uttarakhand/Utt Dookan Adhiniyam/Register to be maintained/FORM G.docx",
    "/Uttarakhand/Utt Dookan Adhiniyam/Register to be maintained/FORM H.docx",
    "/Uttarakhand/Utt Industrial act/FORM II Register of National holidays.docx",
  ],
  "West Bengal": [
    "/West Bengal/BOCW/FORM XIX Fine.xlsx",
    "/West Bengal/BOCW/FORM XV Register of Persons employed.xlsx",
    "/West Bengal/BOCW/FORM XVI Muster.xlsx",
    "/West Bengal/BOCW/FORM XVII Muster roll.xlsx",
    "/West Bengal/BOCW/FORM XVIII Muster roll.xlsx",
    "/West Bengal/BOCW/FORM XX Damges.xlsx",
    "/West Bengal/BOCW/FORM XXI Adanvce.xlsx",
    "/West Bengal/BOCW/FORM XXII Register Of OT.xlsx",
    "/West Bengal/BOCW/FORM XXIII Wage book.xlsx",
    "/West Bengal/BOCW/FORM XXV Annual Return.xlsx",
    "/West Bengal/BOCW/FORM XXVI Register Of Periodical.xlsx",
    "/West Bengal/CLRA/FORM XII Register Of Contractors.docx",
    "/West Bengal/CLRA/FORM XIII Register Of Workmen Employed By Contractor.docx",
    "/West Bengal/CLRA/FORM XIV Employment Card.docx",
    "/West Bengal/CLRA/FORM XVI Muster Roll.docx",
    "/West Bengal/CLRA/FORM XVII Register of Wages.docx",
    "/West Bengal/CLRA/FORM XX Register Of Deductions For Damage Or Loss.docx",
    "/West Bengal/CLRA/FORM XXI Register Of Fines.docx",
    "/West Bengal/CLRA/FORM XXII Register Of Advances.docx",
    "/West Bengal/CLRA/FORM XXIII Register Of Overtime.docx",
    "/West Bengal/CLRA/FORM XXIV Return To Be Sent By The Contractor To The Licencing Officer.docx",
    "/West Bengal/CLRA/FORM XXV Annual Return Of Principal Employer.docx",
    "/West Bengal/CLRA/FORMXIX Wage Slip.docx",
    "/West Bengal/Factory/FORM NO. 10.xlsx",
    "/West Bengal/Factory/FORM NO. 11 Muster roll for Exempted worker.xlsx",
    "/West Bengal/Factory/FORM NO. 17 Pre employment.xlsx",
    "/West Bengal/Factory/FORM NO. 18.xlsx",
    "/West Bengal/Factory/FORM NO. 19.xlsx",
    "/West Bengal/Factory/FORM NO. 22 Annual Return.xlsx",
    "/West Bengal/Factory/FORM NO. 24.xlsx",
    "/West Bengal/Factory/FORM NO. 25 Pre Employment.xlsx",
    "/West Bengal/Factory/FORM NO. 6 Register of washing & painting.xlsx",
    "/West Bengal/Factory/FORM NO. 8A Register of examination lift crances.xlsx",
    "/West Bengal/Factory/FORM NO.12,12A,12B.xlsx",
    "/West Bengal/Factory/FORM NO.13 Register of Adult Workers.xlsx",
    "/West Bengal/Factory/FORM NO.15,16 Leave Register & book.xlsx",
    "/West Bengal/Factory/FORM NO.7 Workers.xlsx",
    "/West Bengal/FORM 6 Register Of Employees ESIC.xls",
    "/West Bengal/FORM A Child Labour act.docx",
    "/West Bengal/FORM A Muster Roll woman Workers.docx",
    "/West Bengal/FORM A Register Of House-Rent Allowance.docx",
    "/West Bengal/FORM B Child Labour act.docx",
    "/West Bengal/FORM D Statement Regarding Contributions LWF.docx",
    "/West Bengal/FORM G Register Of Wages LWF.docx",
    "/West Bengal/FORM J Register Of Employees.docx",
    "/West Bengal/Form XVI Register Of Accounts.xlsx",
    "/West Bengal/Gratuity/FORM I Application For Gratuity By An Employee.docx",
    "/West Bengal/Gratuity/FORM J Application For Gratuity By A Nominee.docx",
    "/West Bengal/Gratuity/FORM K Application For Gratuity By A Legal Heir.docx",
    "/West Bengal/Gratuity/FORM L Notice For Payment Of Gratuity.docx",
    "/West Bengal/Minimum Wages/FORM H Register Of Fines And Unpaid Accumulation LWF.docx",
    "/West Bengal/Minimum Wages/FORM I Register Of Fines.docx",
    "/West Bengal/Minimum Wages/FORM II.docx",
    "/West Bengal/Minimum Wages/FORM III Annual Returns.docx",
    "/West Bengal/Minimum Wages/FORM IV Overtime Register For Workers.docx",
    "/West Bengal/Minimum Wages/FORM V Muster Roll.docx",
    "/West Bengal/Minimum Wages/FORM XIV Register Of Employees.docx",
    "/West Bengal/Minimum Wages/MW-Register of wages.xls",
    "/West Bengal/POW/FORM I Register Of Fines.docx",
    "/West Bengal/POW/FORM II Register Of Damges.docx",
    "/West Bengal/POW/FORM III Register Of Advance.docx",
    "/West Bengal/POW/FORM IV Annual Return.docx",
    "/West Bengal/POW/POW- Register of wages.xls",
    "/West Bengal/S&E/FORM I Register Of Daily Hours Of Work And Rest Intervals.docx",
    "/West Bengal/S&E/FORM J Register Of Leave.docx",
    "/West Bengal/S&E/FORM M Pay Register.docx",
    "/West Bengal/S&E/FORM T Notice Of Overtime.docx",
    "/West Bengal/S&E/FORM U Register Of Overtime Work.docx",
    "/West Bengal/S&E/FORM W Register Of Employees.docx",
  ],
};