export const stateExcelMapping = {
  Central: [
    "/Central/Apprentices/FORM APPRENTICESHIP 1.xlsx",
    "/Central/Apprentices/SCHEDULE I-B.xlsx",
    "/Central/Apprentices/SCHEDULE III FORMAT I.xlsx",
    "/Central/Apprentices/SCHEDULE IV A.xlsx",
    "/Central/Apprentices/SCHEDULE IV.xlsx",
    "/Central/Apprentices/SCHEDULE V.xlsx",
    "/Central/Apprentices/SCHEDULE VI.xlsx",
    "/BOCW/Abstract Under Building And Other Construction Workers (Regulation Of Employment And Conditions Of Service) Act, 1996.xlsx",
    "/BOCW/SCHEDULE II.xlsx",
    "/BOCW/SCHEDULE III First aid box.xlsx",
    "/BOCW/SCHEDULE IV.xlsx",
    "/BOCW/SCHEDULE IX.xlsx",
    "/BOCW/SCHEDULE V.xlsx",
    "/BOCW/SCHEDULE VIII.xlsx",
    "/BOCW/SCHEDULE X.xlsx",
    "/BOCW/SCHEDULE XI.xlsx",
    "/Central/Bonus/FORM A Computation Of The Allocable Surplus.xlsx",
    "/Central/Bonus/FORM B Set-On And Set-Off Of Allocable Surplus.xlsx",
    "/Central/Bonus/FORM C Bonus Paid To Employees.xlsx",
    "/Central/Bonus/Form D.xlsx",
    "/Central/Child/Form A.xlsx",
    "/Central/CLRA Central/Form A.xlsx",
    "/Central/CLRA Central/Form B Overtime.xlsx",
    "/Central/CLRA Central/Form B.xlsx",
    "/Central/CLRA Central/Form C.xlsx",
    "/Central/CLRA Central/Form D.xlsx",
    "/Central/CLRA Central/FORM II (1).xlsx",
    "/Central/CLRA Central/FORM II.xlsx",
    "/Central/CLRA Central/FORM III.xlsx",
    "/Central/CLRA Central/FORM VII (1).xlsx",
    "/Central/CLRA Central/FORM VII (2).xlsx",
    "/Central/CLRA Central/FORM VII (3).xlsx",
    "/Central/CLRA Central/FORM VII.xlsx",
    "/Central/CLRA Central/FORM VIII.xlsx",
    "/Central/CLRA Central/FORM XII Register Of Contractors.xlsx",
    "/Central/CLRA Central/FORM XII.xlsx",
    "/Central/CLRA Central/Form XIII Annexed To The Rationalisation Of Forms And Reports.xlsx",
    "/Central/CLRA Central/Form XIII Register of Workmen.xlsx",
    "/Central/CLRA Central/Form XIV Annexed To The Rationalisation Of Forms And.xlsx",
    "/Central/CLRA Central/Form XIX Wage Slip.xlsx",
    "/Central/CLRA Central/Form XVI Muster Roll.xlsx",
    "/Central/CLRA Central/Form XVII Register of Wages.xlsx",
    "/Central/CLRA Central/Form XX Register of Deduction.xlsx",
    "/Central/CLRA Central/Form XXI Register of Fines.xlsx",
    "/Central/CLRA Central/Form XXII Register of Advances.xlsx",
    "/Central/CLRA Central/Form XXIII Register of Overtime.xlsx",
    "/Central/CLRA Central/Form XXIV Half year return.xlsx",
    "/Central/CLRA Central/Form XXV Annual Return.xlsx",
    "/Central/Compensation/Returns As To Compensation.xlsx",
    "/Central/ESIC/Returns As To Compensation.xlsx",
    "/Central/Gratuity/Display Of Notice.xlsx",
    "/Central/Gratuity/FORM A Notice Of Opening.xlsx",
    "/Central/Gratuity/FORM B Notice Of Change.xlsx",
    "/Central/Gratuity/FORM C Notice Of Closure.xlsx",
    "/Central/Gratuity/FORM F Nomination Form And Updation Of Nomination Form.xlsx",
    "/Central/Gratuity/FORM G Nomination Form And Updation Of Nomination Form.xlsx",
    "/Central/Gratuity/FORM I Payment Of Gratuity.xlsx",
    "/Central/Gratuity/FORM J Payment Of Gratuity.xlsx",
    "/Central/Gratuity/FORM K Payment Of Gratuity.xlsx",
    "/Central/Gratuity/FORM L Payment Of Gratuity.xlsx",
    "/Central/Maternity/FORM A.xlsx",
    "/Central/Maternity/FORM L.xlsx",
    "/Central/Maternity/FORM M.xlsx",
    "/Central/Maternity/FORM N.xlsx",
    "/Central/Maternity/FORM O.xlsx",
    "/Central/Mines/FORM A (1).xlsx",
    "/Central/Mines/FORM A (2).xlsx",
    "/Central/Mines/FORM A.xlsx",
    "/Central/Mines/FORM B.xlsx",
    "/Central/Mines/FORM D.xlsx",
    "/Central/Mines/FORM E (1).xlsx",
    "/Central/Mines/FORM E.xlsx",
    "/Central/Mines/FORM J.xlsx",
    "/Central/Mines/FORM K.xlsx",
    "/Central/Mines/FORM L.xlsx",
    "/Central/Mines/FORM M.xlsx",
    "/Central/Mines/FORM O.xlsx",
    "/Central/Mines/FORM T.xlsx",
    "/Central/PF/FORM 7(IF).xlsx",
    "/Central/PF/Statement IW-1.xlsx",
    "/Central/Sales Promotion/FORM A.xlsx",
    "/Central/Sales Promotion/FORM B.xlsx",
    "/Central/Sales Promotion/FORM C.xlsx",
    "/Central/Sales Promotion/FORM D.xlsx",
    "/Central/Sales Promotion/FORM E.xlsx",
    "/Central/Wages/Form B (1).xlsx",
    "/Central/Wages/Form B (2).xlsx",
    "/Central/Wages/FORM B.xlsx",
    "/Central/Wages/FORM C (1).xlsx",
    "/Central/Wages/FORM C (2) Damges.xlsx",
    "/Central/Wages/FORM C (2) Fine.xlsx",
    "/Central/Wages/Form C (2).xlsx",
    "/Central/Wages/FORM C.xlsx",
    "/Central/Wages/Form D (1).xlsx",
    "/Central/Wages/FORM D.xlsx",
    "/Central/Wages/Form I (1).xlsx",
    "/Central/Wages/Form I (2) Air Tranport.xlsx",
    "/Central/Wages/FORM I (2).xlsx",
    "/Central/Wages/Form I Application for Registration.xlsx",
    "/Central/Wages/Form I.xlsx",
    "/Central/Wages/FORM II.xlsx",
    "/Central/Wages/FORM III Annual Return.xlsx",
    "/Central/Wages/FORM IV.xlsx",
    "/Central/Wages/FORM V master.xlsx",
    "/Central/Wages/FORM VI.xlsx",
    "/Central/Wages/Form VIII.xlsx",
    "/Central/Wages/FORM X.xlsx",
  ],
  Maharashtra: [
    "/Maharashtra/FORM 10 Maternity Benefit Register.docx",
    "/Maharashtra/FORM A-1 LWF.xls",
    "/Maharashtra/FORM B Child labour act.docx",
    "/Maharashtra/FORM B Register Of Wages LWF.docx",
    "/Maharashtra/FORM C Register Of Fines And Unpaid Accumulations LWF.xlsx",
    "/Maharashtra/Form II Muster Roll Cum Wages Register LWF.docx",
    "/Maharashtra/Form III B.docx",

    "/Maharashtra/Allowances/FORM A Register Of House Rent Allowance.docx",
    "/Maharashtra/Allowances/FORM I Register Of Workmen.docx",
    "/Maharashtra/BOCW/FORM IX.xlsx",
    "/Maharashtra/BOCW/FORM X Muster.xlsx",
    "/Maharashtra/BOCW/FORM XI Muster.xlsx",
    "/Maharashtra/BOCW/FORM XII Muster.xlsx",
    "/Maharashtra/BOCW/FORM XIII Fine.xlsx",
    "/Maharashtra/BOCW/FORM XIV Damges.xlsx",
    "/Maharashtra/BOCW/FORM XV advance.xlsx",
    "/Maharashtra/BOCW/FORM XVI overtime.xlsx",
    "/Maharashtra/BOCW/FORM XVII wage book.xlsx",

    "/Maharashtra/CLRA/FORM II Attendance Card Cum Wages Slip.xlsx",
    "/Maharashtra/CLRA/FORM II Muster Roll Cum Wages Register.xlsx",
    "/Maharashtra/CLRA/FORM No.7 Pre employement.xlsx",
    "/Maharashtra/CLRA/FORM VIII Register Of Particulars Of Contractors.docx",
    "/Maharashtra/CLRA/FORM X Identity Card.docx",
    "/Maharashtra/CLRA/FORM XIII Register Of Workmen Employed By Contractor.docx",
    "/Maharashtra/CLRA/FORM XIV Employment Card.docx",
    "/Maharashtra/CLRA/FORM XXIV Return To Be Sent By The Contractor To The Licensing Officer.docx",
    "/Maharashtra/Factory/FORM 17.xlsx",
    "/Maharashtra/Factory/FORM No. 10.xlsx",
    "/Maharashtra/Factory/FORM No. 20.xlsx",
    "/Maharashtra/Factory/FORM No. 29.xlsx",
    "/Maharashtra/Factory/FORM No. 30 accident.xlsx",
    "/Maharashtra/Factory/FORM No.11.xlsx",




    "/Maharashtra/Gartuity/FORM I Application For Gratuity By An Employee.docx",
    "/Maharashtra/Gartuity/FORM J Application For Gratuity By A Nominee.docx",
    "/Maharashtra/Gartuity/FORM K Application For Gratuity By A Legal Heir.docx",
    "/Maharashtra/Gartuity/FORM L Notice For Payment Of Gratuity.docx",
    "/Maharashtra/Gartuity/Form U Abstract Under The Payment Of Gratuity Act, 1972.pdf",
    "/Maharashtra/Gartuity/Form U Abstract Under The Payment Of Gratuity Act,1972 (Marathi Version).pdf",

    "/Maharashtra/Maternity/FORM 1.docx",
    "/Maharashtra/Maternity/FORM 2.docx",
    "/Maharashtra/Maternity/FORM 3.docx",
    "/Maharashtra/Maternity/FORM 4.docx",
    "/Maharashtra/Maternity/FORM 5.docx",
    "/Maharashtra/Maternity/FORM 6.docx",
    "/Maharashtra/Maternity/FORM 7.docx",
    "/Maharashtra/Maternity/FORM 8.docx",
    "/Maharashtra/POw/FORM IV Register Of Advances Made To Employed Persons.docx",
    "/Maharashtra/S&E/FORM H Register Of Employment.xlsx",
    
    "/Maharashtra/S&E/FORM I.docx",
   "/Maharashtra/S&E/FORM II Muster Roll Cum Wage Register.xlsx",
    "/Maharashtra/S&E/FORM J Register Of Employment.docx",
    "/Maharashtra/S&E/FORM K.docx",
    "/Maharashtra/S&E/FORM M.xlsx",
    "/Maharashtra/S&E/FORM O Leave Book.xlsx",
    "/Maharashtra/S&E/FORM P.xlsx",
    "/Maharashtra/S&E/FORM Q Muster.xlsx",
    "/Maharashtra/S&E/FORM-R Annual return.XLSX",





  ],
  Uttarakhand: [
    "/Uttarakhand/FORM A Child Labour act.xlsx",
    "/Uttarakhand/BOCW/FORM XXIII-Wage Book -Uttaranchal BOCW Rules, 2005.xlsx",
    "/Uttarakhand/CLRA/FORM XII Contractor.xlsx",
    "/Uttarakhand/CLRA/FORM XIII Workmen empl.xlsx",
    "/Uttarakhand/CLRA/FORM XIV Employment card.xlsx",
    "/Uttarakhand/CLRA/FORM XIX wage slip.xlsx",
    "/Uttarakhand/CLRA/FORM XVI Muster.xlsx",
    "/Uttarakhand/CLRA/FORM XVII Wages register.xlsx",
    "/Uttarakhand/CLRA/FORM XX Fine.xlsx",
    "/Uttarakhand/CLRA/FORM XXI Damges.xlsx",
    "/Uttarakhand/CLRA/FORM XXII Advance.xlsx",
    "/Uttarakhand/CLRA/FORM XXIII OT.xlsx",
    "/Uttarakhand/CLRA/FORM XXV Annual return.xlsx",
    "/Uttarakhand/Gratuity/FORM I.xlsx",
    "/Uttarakhand/Gratuity/FORM J.xlsx",
    "/Uttarakhand/Gratuity/FORM K.xlsx",
    "/Uttarakhand/Gratuity/FORM L.xlsx",
    "/Uttarakhand/Minimum wages/FORM I Fine.xlsx",
    "/Uttarakhand/Minimum wages/FORM II Damges.xlsx",
    "/Uttarakhand/Minimum wages/FORM III Annual Return.xlsx",
    "/Uttarakhand/Minimum wages/FORM XI Abstract.xlsx",
    "/Uttarakhand/Minimum wages/FORM XII Abstract Under The Minimum Wages Act, 1948.xlsx",
    "/Uttarakhand/Minimum wages/FORM XIII Rate of minimum wages.xlsx",
    "/Uttarakhand/POW/FORM I Fine.xlsx",
    "/Uttarakhand/POW/FORM II Damges.xlsx",
    "/Uttarakhand/POW/FORM III Advance.xlsx",
    "/Uttarakhand/Utt Dookan Adhiniyam/Register to be maintained/FORM A.xlsx",
    "/Uttarakhand/Utt Dookan Adhiniyam/Register to be maintained/FORM B.xlsx",
    "/Uttarakhand/Utt Dookan Adhiniyam/Register to be maintained/FORM CC.xlsx",
    "/Uttarakhand/Utt Dookan Adhiniyam/Register to be maintained/FORM D.xlsx",
    "/Uttarakhand/Utt Dookan Adhiniyam/Register to be maintained/FORM E.xlsx",
    "/Uttarakhand/Utt Dookan Adhiniyam/Register to be maintained/FORM G.xlsx",
    "/Uttarakhand/Utt Dookan Adhiniyam/Register to be maintained/FORM H.xlsx",
    "/Uttarakhand/Utt Industrial act/FORM II Register of National holidays.xlsx",
  ],
  "Uttar Pradesh": [
    "/Uttar Pradesh/FORM A Child Labour Act.xlsx",
    "/Uttar Pradesh/CLRA/FORM XII.xlsx",
    "/Uttar Pradesh/CLRA/FORM XIX wage s.xlsx",
    "/Uttar Pradesh/CLRA/FORM XXIII OT.xlsx",
    "/Uttar Pradesh/Gratuity/FORM I.xlsx",
    "/Uttar Pradesh/Gratuity/FORM J.xlsx",
    "/Uttar Pradesh/Gratuity/FORM K.xlsx",
    "/Uttar Pradesh/Gratuity/FORM L.xlsx",
    "/Uttar Pradesh/Minimum wages/FORM I Fine.xlsx",
    "/Uttar Pradesh/Minimum wages/FORM II.xlsx",
    "/Uttar Pradesh/Minimum wages/FORM III Annual ret.xlsx",
    "/Uttar Pradesh/Minimum wages/FORM IV muster.xlsx",
    "/Uttar Pradesh/Minimum wages/FORM XVII OT.xlsx",
    "/Uttar Pradesh/Minimum wages/Wage Slip under the Uttar Pradesh Minimum Wages Rules, 1959.xlsx",
    "/Uttar Pradesh/POW/FORM I Fine.xlsx",
    "/Uttar Pradesh/POW/FORM II Damges.xlsx",
    "/Uttar Pradesh/POW/FORM III Advances.xlsx",
    "/Uttar Pradesh/POW/FORM IV Annual ret.xlsx",
    "/Uttar Pradesh/UP Dokkan/FORM CC Register of attendance.xlsx",
    "/Uttar Pradesh/UP Dokkan/FORM D.xlsx",
    "/Uttar Pradesh/UP Dokkan/FORM E Fine.xlsx",
    "/Uttar Pradesh/UP Dokkan/FORM G wages register.xlsx",
    "/Uttar Pradesh/UP Dokkan/FORM H.xlsx",
  ],
  "Tamil Nadu": [
    "/Tamil Nadu/CLRA/FORM No. XXIX Register Of Advances, Deductions For Damage.xlsx",
    "/Tamil Nadu/CLRA/FORM No. XXVI Register Of Employment.xlsx",
    "/Tamil Nadu/CLRA/FORM No. XXVII Register Of Wages.xlsx",
    "/Tamil Nadu/CLRA/FORM No. XXVIII Wage Slip.xlsx",
    "/Tamil Nadu/CLRA/FORM XII Register of Contractor.xlsx",
    "/Tamil Nadu/Factory/FORM NO. 7.xlsx",
    "/Tamil Nadu/Factory/FORM NO. 10.xlsx",
    "/Tamil Nadu/Factory/Form No. 12 Audit.xlsx",
    "/Tamil Nadu/Factory/FORM NO. 17 Heath checkup.xlsx",
    "/Tamil Nadu/Factory/FORM NO. 22 Annual Retun.xlsx",
    "/Tamil Nadu/Factory/Form No. 25-A Adult.xlsx",
    "/Tamil Nadu/Factory/FORM NO. 25-C ID.xlsx",
    "/Tamil Nadu/Factory/FORM NO. 27 pre employment.xlsx",
    "/Tamil Nadu/Factory/FORM NO. 28.xlsx",
    "/Tamil Nadu/Factory/FORM NO. 29.xlsx",
    "/Tamil Nadu/Factory/FORM NO. 35.xlsx",
    "/Tamil Nadu/Factory/FORM NO. 36.xlsx",
    "/Tamil Nadu/Factory/FORM NO. 39 Health Register.xlsx",
    "/Tamil Nadu/LWF/FORM A.xlsx",
    "/Tamil Nadu/LWF/FORM B Register Of Wages.xlsx",
    "/Tamil Nadu/LWF/FORM C Register Of Fines And Unpaid Accumulations 1.xlsx",
    "/Tamil Nadu/LWF/FORM C Register Of Fines And Unpaid Accumulations.xlsx",
    "/Tamil Nadu/Minimum wages/FORM I Register Of Fines.xlsx",
    "/Tamil Nadu/Minimum wages/FORM II Register Of Deductions For Damage Or Loss.xlsx",
    "/Tamil Nadu/Minimum wages/FORM III Annual Returns.xlsx",
    "/Tamil Nadu/Minimum wages/FORM IV Overtime Register For Workers.xlsx",
    "/Tamil Nadu/Minimum wages/FORM V Muster.xlsx",
    "/Tamil Nadu/Minimum wages/FORM XI Register of Employees.xlsx",
    "/Tamil Nadu/Minimum wages/Wage Slip under the Minimum Wages (Tamil Nadu) Rules, 1953.xlsx",
    "/Tamil Nadu/POW/Display of Notice under of Payment of wages act.xlsx",
    "/Tamil Nadu/POW/FORM I Fine.xlsx",
    "/Tamil Nadu/POW/FORM I Nomination and Declaration Form.xlsx",
    "/Tamil Nadu/POW/FORM II Damges.xlsx",
    "/Tamil Nadu/POW/FORM III Advance.xlsx",
    "/Tamil Nadu/POW/FORM IV Annual ret.xlsx",
    "/Tamil Nadu/POW/FORM V Abstract Of Payment Of Wages Act And Rules.xlsx",
    "/Tamil Nadu/POW/FORM VI Wages Rate.xlsx",
    "/Tamil Nadu/POW/FORM VIII.xlsx",
    "/Tamil Nadu/POW/Wage Slip under the Tamil Nadu Payment Of Wages Rules, 1937.xlsx",
    "/Tamil Nadu/S&E/FORM R.xlsx",
    "/Tamil Nadu/S&E/FORM T Wage slip.xlsx",
    "/Tamil Nadu/Tamil nadu Industrial act/FORM A Muster Roll woman worker.xlsx",
    "/Tamil Nadu/Tamil nadu Industrial act/FORM No. VI.xlsx",
    "/Tamil Nadu/Abstract Of Child And Adolescent Labour Prohibition And Regulation Act 1986.xlsx",
    "/Tamil Nadu/FORM 2 Child labour act.xlsx",
  ],
  "Andhra Pradesh": [
    "/Andhra Pradesh/BOCW/Andhra Pradesh (Issuance Of Integrated Registration And Furnishing Of Combined Returns Under Various Labour Laws By Certain Establishments) Act, 2015.xlsx",
    "/Andhra Pradesh/BOCW/AP_Construction_Workers_Cess_Notification.xlsx",
    "/Andhra Pradesh/Child Labour/Abstract of Child and Adolescent Labour Prohibition And Regulation Act 1986.pdf",

    "/Andhra Pradesh/Child Labour/Abstract of Child Labour Prohibition And Regulation Act 1986 (Telugu Version).pdf",
    "/Andhra Pradesh/Child Labour/Child Labour Notice.docx",
    "/Andhra Pradesh/Child Labour/FORM A.xlsx",
    "/Andhra Pradesh/CLRA/Abstract Of The Contract Labour (Regulation And Abolition) Act, 1970 And The Contract Labour (Regulation And Abolition) Central Rules, 1971 (English Ver.xlsx",
    "/Andhra Pradesh/CLRA/Andhra Pradesh (Issuance Of Integrated Registration And Furnishing Of Combined Returns Under Various Labour Laws By Certain Establishments) Act, 2015.xlsx",
    "/Andhra Pradesh/CLRA/Display Of Notice Regarding Rates Of Wages Etc-Andhra Pradesh.xlsx",
    "/Andhra Pradesh/CLRA/FORM A.xlsx",
    "/Andhra Pradesh/CLRA/FORM B.xlsx",
    "/Andhra Pradesh/CLRA/FORM C.xlsx",
    "/Andhra Pradesh/CLRA/FORM IV.xlsx",
    "/Andhra Pradesh/CLRA/FORM V.xlsx",
    "/Andhra Pradesh/CLRA/FORM VI A (1).xlsx",
    "/Andhra Pradesh/CLRA/FORM VI A.xlsx",
    "/Andhra Pradesh/CLRA/FORM VI-B (1).xlsx",
    "/Andhra Pradesh/CLRA/FORM VI-B.xlsx",
    "/Andhra Pradesh/CLRA/FORM VII (1).xlsx",
    "/Andhra Pradesh/CLRA/FORM VII.xlsx",
    "/Andhra Pradesh/CLRA/FORM XII.xlsx",
    "/Andhra Pradesh/CLRA/FORM XIII.xlsx",
    "/Andhra Pradesh/CLRA/FORM XIV.xlsx",
    "/Andhra Pradesh/CLRA/FORM XV.xlsx",
    "/Andhra Pradesh/CLRA/FORM XVI.xlsx",
    "/Andhra Pradesh/CLRA/FORM XVII.xlsx",
    "/Andhra Pradesh/CLRA/FORM XX.xlsx",
    "/Andhra Pradesh/CLRA/FORM XXI.xlsx",
    "/Andhra Pradesh/Compession/FORM A.docx",
    "/Andhra Pradesh/Compession/FORM D.docx",
    "/Andhra Pradesh/Compession/FORM EE Report Of Fatal Accidents.docx",
    "/Andhra Pradesh/Compession/FORM F.docx",
    "/Andhra Pradesh/Factory/FORM I.docx",
    "/Andhra Pradesh/Factory/FORM II.docx",
    "/Andhra Pradesh/Factory/FORM NO 8B.docx",
    "/Andhra Pradesh/Factory/FORM NO.5.docx",
    "/Andhra Pradesh/Factory/FORM NO.8A.docx",
    "/Andhra Pradesh/Factory/GNT1720 Employment Of Women During Night Shift In Factories In Andhra Pradesh.pdf",
    "/Andhra Pradesh/Gartiuty/FORM C Notice Of Closure.docx",
    "/Andhra Pradesh/Gartiuty/FORM F Nomination Form.docx",
    "/Andhra Pradesh/Gartiuty/FORM G Fresh Nomination.docx",
    "/Andhra Pradesh/Gartiuty/FORM I Application For Gratuity By An Employee.docx",
    "/Andhra Pradesh/Gartiuty/FORM J Application For Gratuity By A Nominee.docx",
    "/Andhra Pradesh/Gartiuty/FORM K Application For Gratuity By A Legal Heir.docx",
    "/Andhra Pradesh/Gartiuty/FORM L Notice For Payment Of Gratuity.docx",
    "/Andhra Pradesh/Gartiuty/Notice of Authorised Person under PoG Act (English).doc",
    "/Andhra Pradesh/Gartiuty/Notice of Authorised Person under PoG Act (Telugu).doc",

    "/Andhra Pradesh/Industrial/FORM A.docx",
    "/Andhra Pradesh/Industrial/FORM B.docx",
    "/Andhra Pradesh/Industrial/FORM I (1).docx",
    "/Andhra Pradesh/Industrial/FORM II.docx",
    "/Andhra Pradesh/Industrial/Schedule I.docx",
    "/Andhra Pradesh/LWF/FORM A (1).docx",
    "/Andhra Pradesh/LWF/FORM D.docx",
    "/Andhra Pradesh/LWF/FORM E.docx",
    "/Andhra Pradesh/LWF/FORM G.docx",
    "/Andhra Pradesh/LWF/FORM F.xlsx",
    
    "/Andhra Pradesh/Shop & est/FORM X.docx",
    "/Andhra Pradesh/Shop & est/FORM XI.docx",
    "/Andhra Pradesh/Shop & est/FORM XII.docx",
    "/Andhra Pradesh/Shop & est/FORM XXII.docx",
    "/Andhra Pradesh/Shop & est/FORM XXIII.docx",
    "/Andhra Pradesh/Shop & est/FORM XXIV.docx",
    "/Andhra Pradesh/Shop & est/FORM XXVI.docx",
    "/Andhra Pradesh/Shop & est/FORM XXVII.docx",
  ],
  "Arunachal Pradesh": [
    "/Arunachal Pradesh/FORM 6 Register Of Employees ESIC.xlsx",
  ],
  Assam: [
    "/Assam/FORM 25 Muster Factories.xlsx",
    "/Assam/Form G Woman Muster.xlsx",
    "/Assam/Form I Fine.xlsx",
    "/Assam/Form I.xlsx",
    "/Assam/Form II Damges.xlsx",
    "/Assam/Form II.xlsx",
    "/Assam/Form III Advance.xlsx",
    "/Assam/Form IV Annual Retrun.xlsx",
    "/Assam/Form IV overtime.xlsx",
    "/Assam/FORM IV-A Wages.xlsx",
    "/Assam/Form V Muster.xlsx",
    "/Assam/PoW Register of wages.xls",
  ],
  Bihar: [
    "/Bihar/BOCW/Form XIX Fine.xlsx",
    "/Bihar/BOCW/Form XVI Muster.XLSX",
    "/Bihar/BOCW/Form XVII Muster.XLSX",
    "/Bihar/BOCW/Form XVIII Muster.XLSX",
    "/Bihar/BOCW/Form XX Damges.xlsx",
    "/Bihar/BOCW/Form XXI ADavances.XLSX",
    "/Bihar/BOCW/Form XXII Overtime.xlsx",
    "/Bihar/BOCW/Form XXIII.xlsx",
  ],
  Chhattisgarh: ["/Chhattisgarh/FORM 6 Register Of Employees ESIC.xls"],
  Goa: ["/Goa/FORM 6 Register Of Employees ESIC.xls"],
  Gujarat: ["/Gujarat/FORM 6 Register Of Employees ESIC.xls"],
  Haryana: ["/Haryana/FORM 6 Register Of Employees ESIC.xls"],
  "Himachal Pradesh": [
    "/Himachal Pradesh/FORM 6 Register Of Employees ESIC.xls",
  ],
  Jharkhand: ["/Jharkhand/FORM 6 Register Of Employees ESIC.xls"],
  Karnataka: ["/Karnataka/FORM 6 Register Of Employees ESIC.xls"],
  Kerala: ["/Kerala/FORM 6 Register Of Employees ESIC.xls"],
  "Madhya Pradesh": ["/Madhya Pradesh/FORM 6 Register Of Employees ESIC.xls"],
  Manipur: ["/Manipur/FORM 6 Register Of Employees ESIC.xlsx"],
  Meghalaya: ["/Meghalaya/FORM 6 Register Of Employees ESIC.xls"],
  Mizoram: ["/Mizoram/FORM 6 Register Of Employees ESIC.xls"],
  Nagaland: ["/Nagaland/FORM 6 Register Of Employees ESIC.xls"],
  Odisha: ["/Odisha/FORM 6 Register Of Employees ESIC.xls"],
  Punjab: ["/Punjab/FORM 6 Register Of Employees ESIC.xls"],
  Rajasthan: ["/Rajasthan/FORM 6 Register Of Employees ESIC.xls"],
  Sikkim: ["/Sikkim/FORM 6 Register Of Employees ESIC.xls"],
  Telangana: ["/Telangana/FORM 6 Register Of Employees ESIC.xls"],
  Tripura: ["/Tripura/FORM 6 Register Of Employees ESIC.xls"],
  "West Bengal": ["/West Bengal/FORM 6 Register Of Employees ESIC.xls"],
  // Union Territories
  "Andman Nicobar": [
    "/Andman Nicobar/FORM 6 Register Of Employees ESIC.xls",
    "/Andman Nicobar/Form A Shop & Esatbilashment.xlsx",
    "/Andman Nicobar/Form C.xlsx",
    "/Andman Nicobar/Form D Holidays.xlsx",
    "/Andman Nicobar/Form E Holiday.xlsx",
    "/Andman Nicobar/Form F Holidays.xlsx",
    "/Andman Nicobar/Form II Wages silp.xlsx",
    "/Andman Nicobar/Form III Muster Rolll.xlsx",
    "/Andman Nicobar/Form IV Overtime.xlsx",
    "/Andman Nicobar/Form V Leave book.xlsx",
    "/Andman Nicobar/Form VI Employee register.xlsx",
    "/Andman Nicobar/FORM XII.xlsx",
  ],
  Chandigarh: ["/Chandigarh/FORM 6 Register Of Employees ESIC.xls"],
  "Dadra & Nagar Haveli ": [
    "/Dadra & Nagar Haveli/FORM 6 Register Of Employees ESIC.xls",
  ],
  Delhi: ["/Delhi/FORM 6 Register Of Employees ESIC.xls"],
  "Daman Diu": ["/Delhi/FORM 6 Register Of Employees ESIC.xls"],
  "Jammu Kashmir": ["/Jammu Kashmir/FORM 6 Register Of Employees ESIC.xls"],
  Ladakh: ["/Ladakh/FORM 6 Register Of Employees ESIC.xls"],
  Lakshadweep: ["/Lakshadweep/FORM 6 Register Of Employees ESIC.xls"],
  Puducherry: ["/Puducherry/FORM 6 Register Of Employees ESIC.xls"],
};
